// ARGOS Status TEA Tests — Story 14-6
// Risk-based test expansion: boundary conditions, edge cases, priority coverage
// Generated by TEA (Test Architect) workflow

import { describe, it, expect } from 'bun:test'

// Pure-function version of status logic for testability
function computeArgosStatus(params: {
  activeTriggersCount: number
  totalRecentEvents: number
  failedRecentEvents: number
  cronCostMicro: number
  llmCostMicro: number
  lastEventAt: Date | null
  evaluatorLastCheck: Date | null
}) {
  const {
    activeTriggersCount,
    totalRecentEvents,
    failedRecentEvents,
    cronCostMicro,
    llmCostMicro,
    lastEventAt,
    evaluatorLastCheck,
  } = params

  const cronCost = cronCostMicro / 1_000_000
  const llmCost = llmCostMicro / 1_000_000

  let dataOk: boolean
  let dataOkReason: string

  if (activeTriggersCount === 0) {
    dataOk = true
    dataOkReason = '활성 트리거 없음'
  } else if (totalRecentEvents === 0) {
    dataOk = false
    dataOkReason = '활성 트리거 있으나 최근 1시간 이벤트 없음'
  } else if (totalRecentEvents > 0 && failedRecentEvents / totalRecentEvents >= 0.5) {
    dataOk = false
    dataOkReason = `최근 1시간 실패율 ${Math.round(failedRecentEvents / totalRecentEvents * 100)}% (${failedRecentEvents}/${totalRecentEvents}건)`
  } else {
    dataOk = true
    dataOkReason = `최근 1시간 이벤트 ${totalRecentEvents}건, 실패 ${failedRecentEvents}건`
  }

  let aiOk: boolean
  let aiOkReason: string

  if (failedRecentEvents >= 3) {
    aiOk = false
    aiOkReason = `최근 1시간 실패 ${failedRecentEvents}건 (임계값: 3건)`
  } else if (totalRecentEvents > 0 && failedRecentEvents / totalRecentEvents >= 0.5) {
    aiOk = false
    aiOkReason = `최근 1시간 실패율 ${Math.round(failedRecentEvents / totalRecentEvents * 100)}% (${failedRecentEvents}/${totalRecentEvents}건)`
  } else {
    aiOk = true
    aiOkReason = totalRecentEvents > 0
      ? `최근 1시간 실패 ${failedRecentEvents}/${totalRecentEvents}건`
      : '최근 1시간 이벤트 없음'
  }

  let lastCheckAt: string | null = null
  if (evaluatorLastCheck && lastEventAt) {
    lastCheckAt = evaluatorLastCheck > lastEventAt
      ? evaluatorLastCheck.toISOString()
      : lastEventAt.toISOString()
  } else if (evaluatorLastCheck) {
    lastCheckAt = evaluatorLastCheck.toISOString()
  } else if (lastEventAt) {
    lastCheckAt = lastEventAt.toISOString()
  }

  return {
    dataOk,
    aiOk,
    activeTriggersCount,
    todayCost: cronCost + llmCost,
    lastCheckAt,
    dataOkReason,
    aiOkReason,
    costBreakdown: { cronCost, llmCost },
  }
}

// === P0: Critical Boundary Conditions ===

describe('[P0] ARGOS Status - dataOk/aiOk Interaction', () => {
  it('dataOk=false and aiOk=false when 2 total, 1 failed (ratio ≥ 50%, count < 3)', () => {
    const result = computeArgosStatus({
      activeTriggersCount: 1,
      totalRecentEvents: 2,
      failedRecentEvents: 1,
      cronCostMicro: 0,
      llmCostMicro: 0,
      lastEventAt: new Date(),
      evaluatorLastCheck: null,
    })

    expect(result.dataOk).toBe(false) // 50% failure rate
    expect(result.aiOk).toBe(false)   // 50% ratio threshold
  })

  it('dataOk=true and aiOk=false when count threshold hit but ratio < 50%', () => {
    const result = computeArgosStatus({
      activeTriggersCount: 5,
      totalRecentEvents: 10,
      failedRecentEvents: 3,
      cronCostMicro: 0,
      llmCostMicro: 0,
      lastEventAt: new Date(),
      evaluatorLastCheck: null,
    })

    expect(result.dataOk).toBe(true)   // 30% < 50%
    expect(result.aiOk).toBe(false)    // 3 ≥ threshold
  })

  it('dataOk=false and aiOk=true when ratio high but count low and only 1 event', () => {
    // Edge case: 1 total, 0 failed — should both be OK
    const result = computeArgosStatus({
      activeTriggersCount: 3,
      totalRecentEvents: 1,
      failedRecentEvents: 0,
      cronCostMicro: 0,
      llmCostMicro: 0,
      lastEventAt: new Date(),
      evaluatorLastCheck: null,
    })

    expect(result.dataOk).toBe(true)
    expect(result.aiOk).toBe(true)
  })

  it('handles single event single failure correctly', () => {
    const result = computeArgosStatus({
      activeTriggersCount: 1,
      totalRecentEvents: 1,
      failedRecentEvents: 1,
      cronCostMicro: 0,
      llmCostMicro: 0,
      lastEventAt: new Date(),
      evaluatorLastCheck: null,
    })

    expect(result.dataOk).toBe(false)  // 100% failure
    expect(result.aiOk).toBe(false)    // 100% > 50%
  })
})

describe('[P0] ARGOS Status - Threshold Exact Boundaries', () => {
  it('aiOk threshold: exactly 2 failures should be OK', () => {
    const result = computeArgosStatus({
      activeTriggersCount: 5,
      totalRecentEvents: 100,
      failedRecentEvents: 2,
      cronCostMicro: 0,
      llmCostMicro: 0,
      lastEventAt: new Date(),
      evaluatorLastCheck: null,
    })

    expect(result.aiOk).toBe(true)
  })

  it('aiOk threshold: exactly 3 failures should be NG', () => {
    const result = computeArgosStatus({
      activeTriggersCount: 5,
      totalRecentEvents: 100,
      failedRecentEvents: 3,
      cronCostMicro: 0,
      llmCostMicro: 0,
      lastEventAt: new Date(),
      evaluatorLastCheck: null,
    })

    expect(result.aiOk).toBe(false)
  })

  it('dataOk failure rate: 4 of 9 (44%) should be OK', () => {
    const result = computeArgosStatus({
      activeTriggersCount: 3,
      totalRecentEvents: 9,
      failedRecentEvents: 4,
      cronCostMicro: 0,
      llmCostMicro: 0,
      lastEventAt: new Date(),
      evaluatorLastCheck: null,
    })

    expect(result.dataOk).toBe(true) // 44.4% < 50%
  })

  it('dataOk failure rate: 5 of 9 (56%) should be NG', () => {
    const result = computeArgosStatus({
      activeTriggersCount: 3,
      totalRecentEvents: 9,
      failedRecentEvents: 5,
      cronCostMicro: 0,
      llmCostMicro: 0,
      lastEventAt: new Date(),
      evaluatorLastCheck: null,
    })

    expect(result.dataOk).toBe(false) // 55.6% ≥ 50%
  })

  it('ratio boundary: 1 of 2 is exactly 50%', () => {
    const result = computeArgosStatus({
      activeTriggersCount: 1,
      totalRecentEvents: 2,
      failedRecentEvents: 1,
      cronCostMicro: 0,
      llmCostMicro: 0,
      lastEventAt: new Date(),
      evaluatorLastCheck: null,
    })

    expect(result.dataOk).toBe(false) // 50% ≥ 50%
    expect(result.aiOk).toBe(false)   // 50% ≥ 50%
  })
})

// === P1: Cost Edge Cases ===

describe('[P1] ARGOS Status - Cost Edge Cases', () => {
  it('handles very large costs (millions of micro-dollars)', () => {
    const result = computeArgosStatus({
      activeTriggersCount: 0,
      totalRecentEvents: 0,
      failedRecentEvents: 0,
      cronCostMicro: 100_000_000, // $100
      llmCostMicro: 250_000_000,  // $250
      lastEventAt: null,
      evaluatorLastCheck: null,
    })

    expect(result.todayCost).toBe(350)
    expect(result.costBreakdown.cronCost).toBe(100)
    expect(result.costBreakdown.llmCost).toBe(250)
  })

  it('handles fractional micro-dollar costs', () => {
    const result = computeArgosStatus({
      activeTriggersCount: 0,
      totalRecentEvents: 0,
      failedRecentEvents: 0,
      cronCostMicro: 1,
      llmCostMicro: 1,
      lastEventAt: null,
      evaluatorLastCheck: null,
    })

    expect(result.todayCost).toBeCloseTo(0.000002, 6)
  })

  it('cost breakdown sums to todayCost', () => {
    const result = computeArgosStatus({
      activeTriggersCount: 0,
      totalRecentEvents: 0,
      failedRecentEvents: 0,
      cronCostMicro: 3_456_789,
      llmCostMicro: 1_234_567,
      lastEventAt: null,
      evaluatorLastCheck: null,
    })

    expect(result.todayCost).toBeCloseTo(
      result.costBreakdown.cronCost + result.costBreakdown.llmCost,
      10,
    )
  })
})

// === P1: lastCheckAt Edge Cases ===

describe('[P1] ARGOS Status - lastCheckAt Edge Cases', () => {
  it('handles equal timestamps (evaluator == event)', () => {
    const sameTime = new Date('2026-03-08T12:00:00Z')

    const result = computeArgosStatus({
      activeTriggersCount: 0,
      totalRecentEvents: 0,
      failedRecentEvents: 0,
      cronCostMicro: 0,
      llmCostMicro: 0,
      lastEventAt: sameTime,
      evaluatorLastCheck: sameTime,
    })

    // When equal, event time is returned (evaluator > event is false)
    expect(result.lastCheckAt).toBe(sameTime.toISOString())
  })

  it('handles very old timestamps', () => {
    const oldTime = new Date('2020-01-01T00:00:00Z')

    const result = computeArgosStatus({
      activeTriggersCount: 0,
      totalRecentEvents: 0,
      failedRecentEvents: 0,
      cronCostMicro: 0,
      llmCostMicro: 0,
      lastEventAt: oldTime,
      evaluatorLastCheck: null,
    })

    expect(result.lastCheckAt).toBe(oldTime.toISOString())
  })
})

// === P1: Reason String Quality ===

describe('[P1] ARGOS Status - Reason String Formatting', () => {
  it('dataOk reason includes percentage with rounding', () => {
    const result = computeArgosStatus({
      activeTriggersCount: 5,
      totalRecentEvents: 3,
      failedRecentEvents: 2,
      cronCostMicro: 0,
      llmCostMicro: 0,
      lastEventAt: new Date(),
      evaluatorLastCheck: null,
    })

    expect(result.dataOkReason).toContain('67%') // 2/3 = 66.67% -> rounds to 67%
    expect(result.dataOkReason).toContain('2/3건')
  })

  it('aiOk reason for count threshold includes actual count', () => {
    const result = computeArgosStatus({
      activeTriggersCount: 5,
      totalRecentEvents: 50,
      failedRecentEvents: 10,
      cronCostMicro: 0,
      llmCostMicro: 0,
      lastEventAt: new Date(),
      evaluatorLastCheck: null,
    })

    expect(result.aiOkReason).toContain('10건')
    expect(result.aiOkReason).toContain('임계값: 3건')
  })

  it('aiOk reason for ratio includes percentage', () => {
    const result = computeArgosStatus({
      activeTriggersCount: 2,
      totalRecentEvents: 4,
      failedRecentEvents: 2,
      cronCostMicro: 0,
      llmCostMicro: 0,
      lastEventAt: new Date(),
      evaluatorLastCheck: null,
    })

    // 2 failures < 3 threshold, but 50% ratio triggers
    expect(result.aiOkReason).toContain('50%')
  })

  it('dataOk success reason shows exact counts', () => {
    const result = computeArgosStatus({
      activeTriggersCount: 10,
      totalRecentEvents: 100,
      failedRecentEvents: 5,
      cronCostMicro: 0,
      llmCostMicro: 0,
      lastEventAt: new Date(),
      evaluatorLastCheck: null,
    })

    expect(result.dataOkReason).toBe('최근 1시간 이벤트 100건, 실패 5건')
  })
})

// === P2: High Volume Scenarios ===

describe('[P2] ARGOS Status - High Volume', () => {
  it('handles very high event counts', () => {
    const result = computeArgosStatus({
      activeTriggersCount: 100,
      totalRecentEvents: 10000,
      failedRecentEvents: 50,
      cronCostMicro: 0,
      llmCostMicro: 0,
      lastEventAt: new Date(),
      evaluatorLastCheck: new Date(),
    })

    expect(result.dataOk).toBe(true)   // 0.5% failure
    expect(result.aiOk).toBe(false)    // 50 ≥ 3
    expect(result.activeTriggersCount).toBe(100)
  })

  it('handles zero active triggers with events (cleanup state)', () => {
    // Scenario: triggers were deleted but events remain
    const result = computeArgosStatus({
      activeTriggersCount: 0,
      totalRecentEvents: 5,
      failedRecentEvents: 3,
      cronCostMicro: 0,
      llmCostMicro: 0,
      lastEventAt: new Date(),
      evaluatorLastCheck: null,
    })

    expect(result.dataOk).toBe(true)  // No active triggers = OK
    expect(result.aiOk).toBe(false)   // Still checks AI failures regardless
  })
})
