import { describe, expect, it } from 'bun:test'
import { z } from 'zod'

/**
 * Story 2-6: Department Management UI (Admin) -- TEA Risk-Based Test Suite
 * Generated by TEA (Test Architect) automate workflow
 *
 * Risk Coverage:
 * P0 (Critical): Cascade data integrity, delete API contract, modal state machine
 * P1 (Important): Cost calculation edge cases, table mapping, agent counting
 * P2 (Secondary): Form boundary values, UI state transitions, error handling
 */

// === Types ===

type AgentBreakdown = {
  id: string
  name: string
  tier: 'manager' | 'specialist' | 'worker'
  isSystem: boolean
  activeTaskCount: number
  totalCostUsdMicro: number
}

type CascadeAnalysis = {
  departmentId: string
  departmentName: string
  agentCount: number
  activeTaskCount: number
  totalCostUsdMicro: number
  knowledgeCount: number
  agentBreakdown: AgentBreakdown[]
}

type CascadeMode = 'force' | 'wait_completion'
type Department = { id: string; companyId: string; name: string; description: string | null; isActive: boolean; createdAt: string }

// === Extracted logic ===

function formatCost(usdMicro: number): string {
  return `$${(usdMicro / 1_000_000).toFixed(2)}`
}

function buildDeleteUrl(deptId: string, mode: CascadeMode): string {
  return `/admin/departments/${deptId}?mode=${mode}`
}

function agentCountByDept(agents: Array<{ departmentId: string | null }>, deptId: string): number {
  return agents.filter((a) => a.departmentId === deptId).length
}

function buildCascadeAnalysisUrl(deptId: string): string {
  return `/admin/departments/${deptId}/cascade-analysis`
}

// Cascade modal state machine
type CascadeModalState = 'closed' | 'loading' | 'analysis' | 'deleting' | 'error'

function nextModalState(current: CascadeModalState, event: string): CascadeModalState {
  const transitions: Record<string, Record<string, CascadeModalState>> = {
    closed: { open: 'loading' },
    loading: { loaded: 'analysis', error: 'error' },
    analysis: { confirm: 'deleting', cancel: 'closed' },
    deleting: { success: 'closed', error: 'error' },
    error: { retry: 'loading', cancel: 'closed' },
  }
  return transitions[current]?.[event] || current
}

// =============================================
// P0: Cascade Data Integrity
// =============================================
describe('[P0] Cascade analysis data integrity', () => {
  it('should verify agent count matches breakdown length', () => {
    const analysis: CascadeAnalysis = {
      departmentId: 'd1', departmentName: 'Test',
      agentCount: 3, activeTaskCount: 0, totalCostUsdMicro: 0, knowledgeCount: 0,
      agentBreakdown: [
        { id: 'a1', name: 'A1', tier: 'manager', isSystem: false, activeTaskCount: 0, totalCostUsdMicro: 0 },
        { id: 'a2', name: 'A2', tier: 'specialist', isSystem: false, activeTaskCount: 0, totalCostUsdMicro: 0 },
        { id: 'a3', name: 'A3', tier: 'worker', isSystem: true, activeTaskCount: 0, totalCostUsdMicro: 0 },
      ],
    }
    expect(analysis.agentCount).toBe(analysis.agentBreakdown.length)
  })

  it('should verify active task sum equals total', () => {
    const analysis: CascadeAnalysis = {
      departmentId: 'd1', departmentName: 'Test',
      agentCount: 2, activeTaskCount: 7, totalCostUsdMicro: 0, knowledgeCount: 0,
      agentBreakdown: [
        { id: 'a1', name: 'A1', tier: 'manager', isSystem: false, activeTaskCount: 3, totalCostUsdMicro: 0 },
        { id: 'a2', name: 'A2', tier: 'specialist', isSystem: false, activeTaskCount: 4, totalCostUsdMicro: 0 },
      ],
    }
    const sum = analysis.agentBreakdown.reduce((s, a) => s + a.activeTaskCount, 0)
    expect(sum).toBe(analysis.activeTaskCount)
  })

  it('should verify cost sum equals total', () => {
    const analysis: CascadeAnalysis = {
      departmentId: 'd1', departmentName: 'Test',
      agentCount: 2, activeTaskCount: 0, totalCostUsdMicro: 80_000_000, knowledgeCount: 0,
      agentBreakdown: [
        { id: 'a1', name: 'A1', tier: 'manager', isSystem: false, activeTaskCount: 0, totalCostUsdMicro: 50_000_000 },
        { id: 'a2', name: 'A2', tier: 'specialist', isSystem: false, activeTaskCount: 0, totalCostUsdMicro: 30_000_000 },
      ],
    }
    const sum = analysis.agentBreakdown.reduce((s, a) => s + a.totalCostUsdMicro, 0)
    expect(sum).toBe(analysis.totalCostUsdMicro)
  })

  it('should handle all-zero analysis (empty dept)', () => {
    const analysis: CascadeAnalysis = {
      departmentId: 'd1', departmentName: 'Empty',
      agentCount: 0, activeTaskCount: 0, totalCostUsdMicro: 0, knowledgeCount: 0,
      agentBreakdown: [],
    }
    expect(analysis.agentCount).toBe(0)
    expect(analysis.agentBreakdown).toHaveLength(0)
    expect(analysis.totalCostUsdMicro).toBe(0)
  })

  it('should identify departments with only system agents', () => {
    const breakdown: AgentBreakdown[] = [
      { id: 'a1', name: 'Chief', tier: 'manager', isSystem: true, activeTaskCount: 0, totalCostUsdMicro: 0 },
      { id: 'a2', name: 'Secretary', tier: 'worker', isSystem: true, activeTaskCount: 0, totalCostUsdMicro: 0 },
    ]
    const allSystem = breakdown.every(a => a.isSystem)
    expect(allSystem).toBe(true)
  })

  it('should correctly separate system vs non-system agents', () => {
    const breakdown: AgentBreakdown[] = [
      { id: 'a1', name: 'Chief', tier: 'manager', isSystem: true, activeTaskCount: 0, totalCostUsdMicro: 0 },
      { id: 'a2', name: 'Analyst', tier: 'specialist', isSystem: false, activeTaskCount: 2, totalCostUsdMicro: 10_000 },
      { id: 'a3', name: 'Writer', tier: 'worker', isSystem: false, activeTaskCount: 0, totalCostUsdMicro: 5_000 },
    ]
    const systemAgents = breakdown.filter(a => a.isSystem)
    const normalAgents = breakdown.filter(a => !a.isSystem)
    expect(systemAgents).toHaveLength(1)
    expect(normalAgents).toHaveLength(2)
  })
})

// =============================================
// P0: Delete API Contract
// =============================================
describe('[P0] Delete API contract', () => {
  it('should construct cascade analysis URL correctly', () => {
    expect(buildCascadeAnalysisUrl('dept-abc-123')).toBe('/admin/departments/dept-abc-123/cascade-analysis')
  })

  it('should construct force delete URL', () => {
    expect(buildDeleteUrl('d1', 'force')).toBe('/admin/departments/d1?mode=force')
  })

  it('should construct wait_completion delete URL', () => {
    expect(buildDeleteUrl('d1', 'wait_completion')).toBe('/admin/departments/d1?mode=wait_completion')
  })

  it('should handle UUID department IDs', () => {
    const uuid = '550e8400-e29b-41d4-a716-446655440000'
    expect(buildDeleteUrl(uuid, 'force')).toBe(`/admin/departments/${uuid}?mode=force`)
    expect(buildCascadeAnalysisUrl(uuid)).toBe(`/admin/departments/${uuid}/cascade-analysis`)
  })

  it('should validate cascade mode enum', () => {
    const modeSchema = z.enum(['force', 'wait_completion'])
    expect(modeSchema.safeParse('force').success).toBe(true)
    expect(modeSchema.safeParse('wait_completion').success).toBe(true)
    expect(modeSchema.safeParse('soft_delete').success).toBe(false)
    expect(modeSchema.safeParse('').success).toBe(false)
  })
})

// =============================================
// P0: Modal State Machine
// =============================================
describe('[P0] Cascade modal state machine', () => {
  it('should start in closed state', () => {
    expect(nextModalState('closed', 'open')).toBe('loading')
  })

  it('should transition loading -> analysis on success', () => {
    expect(nextModalState('loading', 'loaded')).toBe('analysis')
  })

  it('should transition loading -> error on failure', () => {
    expect(nextModalState('loading', 'error')).toBe('error')
  })

  it('should transition analysis -> deleting on confirm', () => {
    expect(nextModalState('analysis', 'confirm')).toBe('deleting')
  })

  it('should transition analysis -> closed on cancel', () => {
    expect(nextModalState('analysis', 'cancel')).toBe('closed')
  })

  it('should transition deleting -> closed on success', () => {
    expect(nextModalState('deleting', 'success')).toBe('closed')
  })

  it('should transition deleting -> error on failure', () => {
    expect(nextModalState('deleting', 'error')).toBe('error')
  })

  it('should transition error -> loading on retry', () => {
    expect(nextModalState('error', 'retry')).toBe('loading')
  })

  it('should transition error -> closed on cancel', () => {
    expect(nextModalState('error', 'cancel')).toBe('closed')
  })

  it('should stay in same state on invalid event', () => {
    expect(nextModalState('closed', 'confirm')).toBe('closed')
    expect(nextModalState('loading', 'cancel')).toBe('loading')
  })
})

// =============================================
// P1: Cost Calculation Edge Cases
// =============================================
describe('[P1] Cost formatting edge cases', () => {
  it('should handle negative costs (refund scenario)', () => {
    expect(formatCost(-500_000)).toBe('$-0.50')
  })

  it('should handle very small micro amounts', () => {
    expect(formatCost(1)).toBe('$0.00')
    expect(formatCost(100)).toBe('$0.00')
    expect(formatCost(999)).toBe('$0.00')
  })

  it('should handle exact dollar amounts', () => {
    expect(formatCost(1_000_000)).toBe('$1.00')
    expect(formatCost(10_000_000)).toBe('$10.00')
    expect(formatCost(100_000_000)).toBe('$100.00')
  })

  it('should handle fractional cents', () => {
    // toFixed(2) uses banker's rounding: 1.005 -> '$1.00' (rounds down at .5 boundary)
    expect(formatCost(1_005_000)).toBe('$1.00')
    expect(formatCost(1_006_000)).toBe('$1.01')
    expect(formatCost(1_004_999)).toBe('$1.00')
  })

  it('should format costs for display in summary cards', () => {
    const costs = [0, 500_000, 1_000_000, 50_000_000, 120_000_000]
    const formatted = costs.map(formatCost)
    expect(formatted).toEqual(['$0.00', '$0.50', '$1.00', '$50.00', '$120.00'])
  })
})

// =============================================
// P1: Table Data Mapping
// =============================================
describe('[P1] Department table data mapping', () => {
  const departments: Department[] = [
    { id: 'd1', companyId: 'c1', name: '마케팅부', description: '마케팅 담당', isActive: true, createdAt: '2026-01-01' },
    { id: 'd2', companyId: 'c1', name: '개발부', description: null, isActive: true, createdAt: '2026-01-02' },
    { id: 'd3', companyId: 'c1', name: '인사부', description: '인사 관리', isActive: false, createdAt: '2026-01-03' },
  ]

  it('should display department name in table', () => {
    expect(departments.map(d => d.name)).toEqual(['마케팅부', '개발부', '인사부'])
  })

  it('should display description or dash for null', () => {
    const descriptions = departments.map(d => d.description || '-')
    expect(descriptions).toEqual(['마케팅 담당', '-', '인사 관리'])
  })

  it('should display active/inactive status', () => {
    const statuses = departments.map(d => d.isActive ? '활성' : '비활성')
    expect(statuses).toEqual(['활성', '활성', '비활성'])
  })

  it('should filter active departments', () => {
    const active = departments.filter(d => d.isActive)
    expect(active).toHaveLength(2)
  })
})

// =============================================
// P1: Agent Counting
// =============================================
describe('[P1] Agent counting per department', () => {
  const agents = [
    { id: 'a1', departmentId: 'd1' },
    { id: 'a2', departmentId: 'd1' },
    { id: 'a3', departmentId: 'd1' },
    { id: 'a4', departmentId: 'd2' },
    { id: 'a5', departmentId: null },
    { id: 'a6', departmentId: null },
  ]

  it('should count 3 agents for dept d1', () => {
    expect(agentCountByDept(agents, 'd1')).toBe(3)
  })

  it('should count 1 agent for dept d2', () => {
    expect(agentCountByDept(agents, 'd2')).toBe(1)
  })

  it('should count 0 for unknown dept', () => {
    expect(agentCountByDept(agents, 'd99')).toBe(0)
  })

  it('should not count unassigned agents for any dept', () => {
    const total = agentCountByDept(agents, 'd1') + agentCountByDept(agents, 'd2')
    expect(total).toBe(4) // 6 total - 2 unassigned
  })

  it('should handle empty agent list', () => {
    expect(agentCountByDept([], 'd1')).toBe(0)
  })
})

// =============================================
// P2: Form Boundary Values
// =============================================
describe('[P2] Department form boundary values', () => {
  const createSchema = z.object({
    name: z.string().min(1).max(100),
    description: z.string().optional(),
  })

  it('should accept 1-char name (minimum)', () => {
    expect(createSchema.safeParse({ name: 'A' }).success).toBe(true)
  })

  it('should accept 100-char name (maximum)', () => {
    expect(createSchema.safeParse({ name: 'A'.repeat(100) }).success).toBe(true)
  })

  it('should reject 101-char name (over maximum)', () => {
    expect(createSchema.safeParse({ name: 'A'.repeat(101) }).success).toBe(false)
  })

  it('should accept Korean department names', () => {
    expect(createSchema.safeParse({ name: '전략기획부' }).success).toBe(true)
  })

  it('should accept name with special characters', () => {
    expect(createSchema.safeParse({ name: 'R&D / 연구개발' }).success).toBe(true)
  })

  it('should accept empty description (optional)', () => {
    expect(createSchema.safeParse({ name: 'Test' }).success).toBe(true)
  })

  it('should accept description with long text', () => {
    expect(createSchema.safeParse({ name: 'Test', description: '설명 '.repeat(100) }).success).toBe(true)
  })
})

// =============================================
// P2: Edit Form State Transitions
// =============================================
describe('[P2] Edit form state transitions', () => {
  it('should populate edit form from department data', () => {
    const dept = { id: 'd1', name: '마케팅부', description: '마케팅 담당' }
    const editForm = { name: dept.name, description: dept.description || '' }
    expect(editForm.name).toBe('마케팅부')
    expect(editForm.description).toBe('마케팅 담당')
  })

  it('should handle null description in edit form', () => {
    const dept = { id: 'd1', name: '개발부', description: null }
    const editForm = { name: dept.name, description: dept.description || '' }
    expect(editForm.description).toBe('')
  })

  it('should only allow one department in edit mode at a time', () => {
    let editId: string | null = null

    editId = 'd1'
    expect(editId).toBe('d1')

    // Switching to another dept
    editId = 'd2'
    expect(editId).toBe('d2')
    expect(editId).not.toBe('d1')
  })
})

// =============================================
// P2: Error Handling Scenarios
// =============================================
describe('[P2] Error handling scenarios', () => {
  it('should handle cascade analysis API error gracefully', () => {
    // Simulate API error - modal should close
    let cascadeTarget: { id: string } | null = { id: 'd1' }
    const handleError = () => { cascadeTarget = null }

    handleError()
    expect(cascadeTarget).toBeNull()
  })

  it('should handle delete mutation error', () => {
    // Should show error toast but not close modal
    let modalOpen = true
    const handleDeleteError = () => { /* modal stays open */ }

    handleDeleteError()
    expect(modalOpen).toBe(true)
  })

  it('should disable delete button during pending state', () => {
    const isPending = true
    const isDisabled = isPending || false
    expect(isDisabled).toBe(true)
  })

  it('should disable delete button when no cascade data loaded', () => {
    const cascadeData = null
    const isDisabled = !cascadeData
    expect(isDisabled).toBe(true)
  })

  it('should require company selection before showing data', () => {
    const selectedCompanyId: string | null = null
    const shouldShowData = !!selectedCompanyId
    expect(shouldShowData).toBe(false)
  })
})

// =============================================
// P2: Cascade API Response Schema
// =============================================
describe('[P2] API response schema validation', () => {
  const responseSchema = z.object({
    data: z.object({
      departmentId: z.string().uuid(),
      departmentName: z.string(),
      agentCount: z.number().int().min(0),
      activeTaskCount: z.number().int().min(0),
      totalCostUsdMicro: z.number().int().min(0),
      knowledgeCount: z.number().int().min(0),
      agentBreakdown: z.array(z.object({
        id: z.string().uuid(),
        name: z.string(),
        tier: z.enum(['manager', 'specialist', 'worker']),
        isSystem: z.boolean(),
        activeTaskCount: z.number().int().min(0),
        totalCostUsdMicro: z.number().int().min(0),
      })),
    }),
  })

  it('should validate well-formed response', () => {
    const response = {
      data: {
        departmentId: '550e8400-e29b-41d4-a716-446655440000',
        departmentName: '마케팅부',
        agentCount: 1,
        activeTaskCount: 0,
        totalCostUsdMicro: 1000,
        knowledgeCount: 5,
        agentBreakdown: [{
          id: '660e8400-e29b-41d4-a716-446655440001',
          name: 'Agent1',
          tier: 'specialist' as const,
          isSystem: false,
          activeTaskCount: 0,
          totalCostUsdMicro: 1000,
        }],
      },
    }
    expect(responseSchema.safeParse(response).success).toBe(true)
  })

  it('should reject negative agent count', () => {
    const response = {
      data: {
        departmentId: '550e8400-e29b-41d4-a716-446655440000',
        departmentName: 'Test', agentCount: -1, activeTaskCount: 0,
        totalCostUsdMicro: 0, knowledgeCount: 0, agentBreakdown: [],
      },
    }
    expect(responseSchema.safeParse(response).success).toBe(false)
  })

  it('should reject non-integer counts', () => {
    const response = {
      data: {
        departmentId: '550e8400-e29b-41d4-a716-446655440000',
        departmentName: 'Test', agentCount: 1.5, activeTaskCount: 0,
        totalCostUsdMicro: 0, knowledgeCount: 0, agentBreakdown: [],
      },
    }
    expect(responseSchema.safeParse(response).success).toBe(false)
  })
})
