/**
 * Story 8.4: maxDepth 회사별 설정 — TEA Risk-Based Tests
 * Risk-prioritized coverage for handoff depth settings
 * Generated by TEA (Test Architect) automate workflow
 */
import { describe, test, expect, mock, beforeEach } from 'bun:test'

// ─── Mock DB ───
const mockSelect = mock(() => ({ from: mockFrom }))
const mockFrom = mock(() => ({ where: mockWhere }))
const mockWhere = mock(() => ({ limit: mockLimit }))
const mockLimit = mock(() => [{ settings: null }])
const mockUpdate = mock(() => ({ set: mockSet }))
const mockSet = mock(() => ({ where: mockUpdateWhere }))
const mockUpdateWhere = mock(() => Promise.resolve())

mock.module('../../db', () => ({
  db: {
    select: mockSelect,
    update: mockUpdate,
  },
}))

mock.module('../../db/schema', () => ({
  companies: {
    id: 'id',
    settings: 'settings',
  },
}))

mock.module('drizzle-orm', () => ({
  eq: (a: unknown, b: unknown) => ({ _eq: [a, b] }),
}))

import { getMaxHandoffDepth, saveMaxHandoffDepth } from '../../services/handoff-depth-settings'

// ─── TEA P0: Boundary Value Analysis ───

describe('TEA P0: boundary value analysis', () => {
  beforeEach(() => {
    mockLimit.mockReset()
  })

  test('depth exactly at each valid boundary: 1,2,3,4,5,6,7,8,9,10', async () => {
    for (let i = 1; i <= 10; i++) {
      mockLimit.mockReturnValueOnce([{ settings: { maxHandoffDepth: i } }])
      const result = await getMaxHandoffDepth(`company-${i}`)
      expect(result).toBe(i)
    }
  })

  test('depth just below minimum (0) returns default', async () => {
    mockLimit.mockReturnValueOnce([{ settings: { maxHandoffDepth: 0 } }])
    expect(await getMaxHandoffDepth('c')).toBe(5)
  })

  test('depth just above maximum (11) returns default', async () => {
    mockLimit.mockReturnValueOnce([{ settings: { maxHandoffDepth: 11 } }])
    expect(await getMaxHandoffDepth('c')).toBe(5)
  })

  test('negative integer returns default', async () => {
    mockLimit.mockReturnValueOnce([{ settings: { maxHandoffDepth: -100 } }])
    expect(await getMaxHandoffDepth('c')).toBe(5)
  })

  test('very large number returns default', async () => {
    mockLimit.mockReturnValueOnce([{ settings: { maxHandoffDepth: 999999 } }])
    expect(await getMaxHandoffDepth('c')).toBe(5)
  })

  test('NaN returns default', async () => {
    mockLimit.mockReturnValueOnce([{ settings: { maxHandoffDepth: NaN } }])
    expect(await getMaxHandoffDepth('c')).toBe(5)
  })

  test('Infinity returns default', async () => {
    mockLimit.mockReturnValueOnce([{ settings: { maxHandoffDepth: Infinity } }])
    expect(await getMaxHandoffDepth('c')).toBe(5)
  })

  test('null returns default', async () => {
    mockLimit.mockReturnValueOnce([{ settings: { maxHandoffDepth: null } }])
    expect(await getMaxHandoffDepth('c')).toBe(5)
  })

  test('undefined returns default', async () => {
    mockLimit.mockReturnValueOnce([{ settings: { maxHandoffDepth: undefined } }])
    expect(await getMaxHandoffDepth('c')).toBe(5)
  })

  test('boolean true returns default', async () => {
    mockLimit.mockReturnValueOnce([{ settings: { maxHandoffDepth: true } }])
    expect(await getMaxHandoffDepth('c')).toBe(5)
  })

  test('array returns default', async () => {
    mockLimit.mockReturnValueOnce([{ settings: { maxHandoffDepth: [5] } }])
    expect(await getMaxHandoffDepth('c')).toBe(5)
  })

  test('object returns default', async () => {
    mockLimit.mockReturnValueOnce([{ settings: { maxHandoffDepth: { value: 5 } } }])
    expect(await getMaxHandoffDepth('c')).toBe(5)
  })
})

// ─── TEA P0: Save Validation Exhaustive ───

describe('TEA P0: save validation exhaustive', () => {
  beforeEach(() => {
    mockLimit.mockReset()
    mockUpdate.mockClear()
    mockSet.mockClear()
  })

  test('save each valid boundary 1-10', async () => {
    for (let i = 1; i <= 10; i++) {
      mockLimit.mockReturnValueOnce([{ settings: {} }])
      mockUpdate.mockClear()
      const result = await saveMaxHandoffDepth('c', i)
      expect(result).toBe(i)
    }
  })

  test('rejects NaN', async () => {
    await expect(saveMaxHandoffDepth('c', NaN)).rejects.toThrow()
  })

  test('rejects Infinity', async () => {
    await expect(saveMaxHandoffDepth('c', Infinity)).rejects.toThrow()
  })

  test('rejects negative Infinity', async () => {
    await expect(saveMaxHandoffDepth('c', -Infinity)).rejects.toThrow()
  })
})

// ─── TEA P1: JSONB Merge Safety ───

describe('TEA P1: JSONB merge safety', () => {
  beforeEach(() => {
    mockLimit.mockReset()
    mockSet.mockClear()
  })

  test('preserves deeply nested existing settings', async () => {
    const complexSettings = {
      promptGuard: { enabled: true, sensitivityLevel: 'moderate', customWhitelist: ['test'] },
      timezone: 'Asia/Seoul',
      defaultModel: 'claude-sonnet-4-20250514',
      dashboardQuickActions: { items: [1, 2, 3] },
    }
    mockLimit.mockReturnValueOnce([{ settings: complexSettings }])
    await saveMaxHandoffDepth('c', 7)
    const setArg = mockSet.mock.calls[0][0] as { settings: Record<string, unknown> }
    expect(setArg.settings.promptGuard).toEqual(complexSettings.promptGuard)
    expect(setArg.settings.timezone).toBe('Asia/Seoul')
    expect(setArg.settings.dashboardQuickActions).toEqual(complexSettings.dashboardQuickActions)
    expect(setArg.settings.maxHandoffDepth).toBe(7)
  })

  test('does not lose existing maxHandoffDepth siblings', async () => {
    mockLimit.mockReturnValueOnce([{ settings: { maxHandoffDepth: 3, somethingElse: true } }])
    await saveMaxHandoffDepth('c', 9)
    const setArg = mockSet.mock.calls[0][0] as { settings: Record<string, unknown> }
    expect(setArg.settings.somethingElse).toBe(true)
    expect(setArg.settings.maxHandoffDepth).toBe(9)
  })

  test('empty object settings → only maxHandoffDepth', async () => {
    mockLimit.mockReturnValueOnce([{ settings: {} }])
    await saveMaxHandoffDepth('c', 5)
    const setArg = mockSet.mock.calls[0][0] as { settings: Record<string, unknown> }
    expect(Object.keys(setArg.settings)).toEqual(['maxHandoffDepth'])
    expect(setArg.settings.maxHandoffDepth).toBe(5)
  })
})

// ─── TEA P1: call-agent depth boundary interaction ───

describe('TEA P1: call-agent depth boundary interaction', () => {
  test('call-agent.ts checks ctx.depth >= ctx.maxDepth (source verification)', async () => {
    const fs = await import('fs')
    const source = fs.readFileSync(
      new URL('../../tool-handlers/builtins/call-agent.ts', import.meta.url).pathname,
      'utf-8',
    )
    expect(source).toContain('ctx.depth >= ctx.maxDepth')
  })

  test('hub.ts no longer has hardcoded maxDepth: 3', async () => {
    const fs = await import('fs')
    const source = fs.readFileSync(
      new URL('../../routes/workspace/hub.ts', import.meta.url).pathname,
      'utf-8',
    )
    // Should NOT contain maxDepth: 3 (now dynamic)
    expect(source).not.toMatch(/maxDepth:\s*3/)
    // Should contain getMaxHandoffDepth call
    expect(source).toContain('getMaxHandoffDepth')
  })

  test('argos-evaluator no longer has hardcoded maxDepth: 3', async () => {
    const fs = await import('fs')
    const source = fs.readFileSync(
      new URL('../../services/argos-evaluator.ts', import.meta.url).pathname,
      'utf-8',
    )
    expect(source).not.toMatch(/maxDepth:\s*3/)
    expect(source).toContain('getMaxHandoffDepth')
  })
})

// ─── TEA P1: Route module structure ───

describe('TEA P1: route module structure', () => {
  test('companySettingsRoute is a Hono instance', async () => {
    const mod = await import('../../routes/admin/company-settings')
    expect(mod.companySettingsRoute).toBeDefined()
    // Hono instances have .routes property
    expect(typeof mod.companySettingsRoute.get).toBe('function')
    expect(typeof mod.companySettingsRoute.put).toBe('function')
  })

  test('index.ts registers companySettingsRoute', async () => {
    const fs = await import('fs')
    const source = fs.readFileSync(
      new URL('../../index.ts', import.meta.url).pathname,
      'utf-8',
    )
    expect(source).toContain("import { companySettingsRoute } from './routes/admin/company-settings'")
    expect(source).toContain("app.route('/api/admin', companySettingsRoute)")
  })
})

// ─── TEA P2: Shared type contract ───

describe('TEA P2: shared type contract', () => {
  test('HandoffDepthSettings has maxHandoffDepth field', async () => {
    const fs = await import('fs')
    const source = fs.readFileSync(
      new URL('../../../../shared/src/types.ts', import.meta.url).pathname,
      'utf-8',
    )
    expect(source).toContain('export interface HandoffDepthSettings')
    expect(source).toContain('maxHandoffDepth: number')
  })
})

// ─── TEA P2: Error resilience ───

describe('TEA P2: error resilience', () => {
  beforeEach(() => {
    mockLimit.mockReset()
  })

  test('DB timeout → returns default', async () => {
    mockLimit.mockImplementationOnce(() => {
      throw new Error('Connection timeout after 5000ms')
    })
    expect(await getMaxHandoffDepth('c')).toBe(5)
  })

  test('DB constraint violation on save → propagates error', async () => {
    mockLimit.mockReturnValueOnce([{ settings: {} }])
    mockUpdateWhere.mockImplementationOnce(() => {
      throw new Error('unique_violation')
    })
    await expect(saveMaxHandoffDepth('c', 5)).rejects.toThrow('unique_violation')
  })
})
