/**
 * LLM Router -- TEA Risk-Based Tests
 * Story 3-2: Edge cases, error resilience, concurrent scenarios
 *
 * Generated by TEA (Test Architect) -- risk-based coverage expansion
 * bun test src/__tests__/unit/llm-router-tea.test.ts
 */
import { describe, test, expect, mock, beforeEach } from 'bun:test'
import type { LLMResponse, LLMStreamChunk, LLMProviderName } from '@corthex/shared'

// === Mock Setup ===

const mockGetCredentials = mock(() => Promise.resolve({ api_key: 'test-key' }))
const mockRecordCost = mock(() => Promise.resolve())
const mockAdapterCall = mock((): Promise<LLMResponse> =>
  Promise.resolve({
    content: 'test',
    toolCalls: [],
    usage: { inputTokens: 50, outputTokens: 25 },
    model: 'claude-sonnet-4-6',
    provider: 'anthropic' as LLMProviderName,
    finishReason: 'stop' as const,
  }),
)

const mockStreamFn = async function* (): AsyncGenerator<LLMStreamChunk> {
  yield { type: 'text', content: 'chunk1' }
  yield { type: 'done', usage: { inputTokens: 30, outputTokens: 15 } }
}

const mockCreateProvider = mock(() => ({
  name: 'anthropic' as LLMProviderName,
  supportsBatch: true,
  call: mockAdapterCall,
  stream: mockStreamFn,
  estimateCost: () => 0,
}))

mock.module('../../services/credential-vault', () => ({
  getCredentials: mockGetCredentials,
}))
mock.module('../../lib/cost-tracker', () => ({
  recordCost: mockRecordCost,
  calculateCostMicro: () => 100,
  microToUsd: (m: number) => m / 1_000_000,
}))
mock.module('../../lib/llm/index', () => ({
  createProvider: mockCreateProvider,
}))

import { LLMRouter, resolveModel, resolveProvider } from '../../services/llm-router'
import type { LLMRouterContext } from '../../services/llm-router'

function ctx(overrides?: Partial<LLMRouterContext>): LLMRouterContext {
  return { companyId: 'co-1', source: 'chat', ...overrides }
}

// === P0: Critical Path Risk Tests ===

describe('TEA P0: Cost recording resilience', () => {
  let router: LLMRouter

  beforeEach(() => {
    router = new LLMRouter()
    mockGetCredentials.mockImplementation(() => Promise.resolve({ api_key: 'k' }))
    mockAdapterCall.mockImplementation(() =>
      Promise.resolve({
        content: 'ok', toolCalls: [], usage: { inputTokens: 10, outputTokens: 5 },
        model: 'claude-sonnet-4-6', provider: 'anthropic' as LLMProviderName, finishReason: 'stop' as const,
      }),
    )
    mockCreateProvider.mockImplementation(() => ({
      name: 'anthropic' as LLMProviderName, supportsBatch: true,
      call: mockAdapterCall, stream: mockStreamFn, estimateCost: () => 0,
    }))
  })

  test('call succeeds even when cost recording throws', async () => {
    mockRecordCost.mockImplementation(() => Promise.reject(new Error('DB connection lost')))

    const response = await router.call(
      { model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'hi' }] },
      ctx(),
    )

    // Call should succeed despite cost recording failure
    expect(response.content).toBe('ok')
  })

  test('stream completes even when cost recording throws', async () => {
    mockRecordCost.mockImplementation(() => Promise.reject(new Error('DB down')))

    const chunks: LLMStreamChunk[] = []
    for await (const chunk of router.stream(
      { model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'hi' }] },
      ctx(),
    )) {
      chunks.push(chunk)
    }

    expect(chunks.length).toBeGreaterThan(0)
  })
})

describe('TEA P0: Credential vault error handling', () => {
  let router: LLMRouter

  beforeEach(() => {
    router = new LLMRouter()
    mockCreateProvider.mockImplementation(() => ({
      name: 'anthropic' as LLMProviderName, supportsBatch: true,
      call: mockAdapterCall, stream: mockStreamFn, estimateCost: () => 0,
    }))
  })

  test('call propagates credential vault errors', async () => {
    mockGetCredentials.mockImplementation(() => Promise.reject(new Error('TOOL_001')))

    try {
      await router.call(
        { model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'hi' }] },
        ctx(),
      )
      expect(true).toBe(false)
    } catch (err: any) {
      expect(err.message).toContain('TOOL_001')
    }
  })

  test('stream propagates credential vault errors', async () => {
    mockGetCredentials.mockImplementation(() => Promise.reject(new Error('TOOL_001')))

    try {
      const gen = router.stream(
        { model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'hi' }] },
        ctx(),
      )
      for await (const _ of gen) { /* consume */ }
      expect(true).toBe(false)
    } catch (err: any) {
      expect(err.message).toContain('TOOL_001')
    }
  })

  test('call with credentials returning empty object throws auth_error', async () => {
    mockGetCredentials.mockImplementation(() => Promise.resolve({}))

    try {
      await router.call(
        { model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'hi' }] },
        ctx(),
      )
      expect(true).toBe(false)
    } catch (err: any) {
      expect(err.code).toBe('auth_error')
    }
  })
})

// === P1: Model Resolution Edge Cases ===

describe('TEA P1: resolveModel edge cases', () => {
  test('all 3 tiers have defined defaults', () => {
    const tiers = ['manager', 'specialist', 'worker'] as const
    for (const tier of tiers) {
      const result = resolveModel({ tier, modelName: null })
      expect(result.model).toBeTruthy()
      expect(result.reason).toBe('tier-default')
    }
  })

  test('worker with sonnet override returns sonnet', () => {
    const result = resolveModel({ tier: 'worker', modelName: 'claude-sonnet-4-6' })
    expect(result.model).toBe('claude-sonnet-4-6')
    expect(result.reason).toBe('manual-override')
  })

  test('specialist with empty string gets tier default', () => {
    const result = resolveModel({ tier: 'specialist', modelName: '' as any })
    expect(result.reason).toBe('tier-default')
  })

  test('manager always gets sonnet as tier default, not haiku', () => {
    // This is the critical edge case: DB default is haiku,
    // but manager tier should get sonnet
    const result = resolveModel({ tier: 'manager', modelName: 'claude-haiku-4-5' })
    expect(result.model).toBe('claude-sonnet-4-6')
    expect(result.model).not.toBe('claude-haiku-4-5')
  })
})

describe('TEA P1: resolveProvider edge cases', () => {
  test('all models in models.yaml resolve to valid providers', () => {
    const models = [
      'claude-sonnet-4-6', 'claude-haiku-4-5',
      'gpt-4.1', 'gpt-4.1-mini',
    ]
    const validProviders: LLMProviderName[] = ['anthropic', 'openai']

    for (const model of models) {
      const provider = resolveProvider(model)
      expect(validProviders).toContain(provider)
    }
  })

  test('throws with descriptive message for unknown model', () => {
    try {
      resolveProvider('llama-3.1-70b')
      expect(true).toBe(false)
    } catch (err: any) {
      expect(err.message).toContain('llama-3.1-70b')
      expect(err.code).toBe('invalid_request')
    }
  })
})

// === P1: Multiple Sequential Calls ===

describe('TEA P1: Sequential multi-provider routing', () => {
  let router: LLMRouter

  beforeEach(() => {
    router = new LLMRouter()
    mockGetCredentials.mockImplementation(() => Promise.resolve({ api_key: 'k' }))
    mockRecordCost.mockImplementation(() => Promise.resolve())
    mockAdapterCall.mockImplementation(() =>
      Promise.resolve({
        content: 'ok', toolCalls: [], usage: { inputTokens: 10, outputTokens: 5 },
        model: 'claude-sonnet-4-6', provider: 'anthropic' as LLMProviderName, finishReason: 'stop' as const,
      }),
    )
    mockCreateProvider.mockImplementation(() => ({
      name: 'anthropic' as LLMProviderName, supportsBatch: true,
      call: mockAdapterCall, stream: mockStreamFn, estimateCost: () => 0,
    }))
  })

  test('can route to different providers sequentially', async () => {
    mockGetCredentials.mockClear()

    // Call 1: anthropic
    await router.call(
      { model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'a' }] },
      ctx(),
    )

    // Call 2: openai
    await router.call(
      { model: 'gpt-4.1', messages: [{ role: 'user', content: 'b' }] },
      ctx(),
    )

    // Verify both providers were called with correct credential keys
    const credCalls = mockGetCredentials.mock.calls
    expect(credCalls).toHaveLength(2)
    expect(credCalls[0][1]).toBe('anthropic')
    expect(credCalls[1][1]).toBe('openai')
  })

  test('each call creates a new adapter (no caching)', async () => {
    mockCreateProvider.mockClear()

    await router.call(
      { model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'a' }] },
      ctx(),
    )
    await router.call(
      { model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'b' }] },
      ctx(),
    )

    // createProvider called twice even for same model (per-request for key rotation)
    expect(mockCreateProvider.mock.calls).toHaveLength(2)
  })
})

// === P1: Stream Error Handling ===

describe('TEA P1: Stream error mid-stream', () => {
  let router: LLMRouter

  beforeEach(() => {
    router = new LLMRouter()
    mockGetCredentials.mockImplementation(() => Promise.resolve({ api_key: 'k' }))
    mockRecordCost.mockImplementation(() => Promise.resolve())
  })

  test('propagates error thrown mid-stream', async () => {
    const errorStream = async function* (): AsyncGenerator<LLMStreamChunk> {
      yield { type: 'text', content: 'start' }
      throw new Error('Connection reset')
    }

    mockCreateProvider.mockImplementation(() => ({
      name: 'anthropic' as LLMProviderName, supportsBatch: true,
      call: mockAdapterCall, stream: errorStream, estimateCost: () => 0,
    }))

    const chunks: LLMStreamChunk[] = []
    try {
      for await (const chunk of router.stream(
        { model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'hi' }] },
        ctx(),
      )) {
        chunks.push(chunk)
      }
      expect(true).toBe(false)
    } catch (err: any) {
      // Should have received the first chunk before error
      expect(chunks).toHaveLength(1)
      expect(chunks[0].content).toBe('start')
      expect(err.provider).toBe('anthropic')
    }
  })
})

// === P2: Context Validation ===

describe('TEA P2: Context with optional fields', () => {
  let router: LLMRouter

  beforeEach(() => {
    router = new LLMRouter()
    mockGetCredentials.mockImplementation(() => Promise.resolve({ api_key: 'k' }))
    mockRecordCost.mockImplementation(() => Promise.resolve())
    mockAdapterCall.mockImplementation(() =>
      Promise.resolve({
        content: 'ok', toolCalls: [], usage: { inputTokens: 10, outputTokens: 5 },
        model: 'claude-sonnet-4-6', provider: 'anthropic' as LLMProviderName, finishReason: 'stop' as const,
      }),
    )
    mockCreateProvider.mockImplementation(() => ({
      name: 'anthropic' as LLMProviderName, supportsBatch: true,
      call: mockAdapterCall, stream: mockStreamFn, estimateCost: () => 0,
    }))
  })

  test('call succeeds with minimal context (companyId + source only)', async () => {
    const response = await router.call(
      { model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'hi' }] },
      { companyId: 'co-1', source: 'delegation' },
    )
    expect(response.content).toBe('ok')
  })

  test('cost recording passes undefined for optional context fields', async () => {
    mockRecordCost.mockClear()

    await router.call(
      { model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'hi' }] },
      { companyId: 'co-1', source: 'job' },
    )

    await new Promise(r => setTimeout(r, 10))

    expect(mockRecordCost).toHaveBeenCalledWith(
      expect.objectContaining({
        companyId: 'co-1',
        agentId: undefined,
        sessionId: undefined,
        source: 'job',
      }),
    )
  })

  test('all source types are accepted', async () => {
    const sources = ['chat', 'delegation', 'job', 'sns'] as const
    for (const source of sources) {
      const response = await router.call(
        { model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'hi' }] },
        { companyId: 'co-1', source },
      )
      expect(response.content).toBe('ok')
    }
  })
})

// === P2: Error Message Sanitization ===

describe('TEA P2: API key sanitization in errors', () => {
  let router: LLMRouter

  beforeEach(() => {
    router = new LLMRouter()
    mockGetCredentials.mockImplementation(() => Promise.resolve({ api_key: 'k' }))
    mockCreateProvider.mockImplementation(() => ({
      name: 'anthropic' as LLMProviderName, supportsBatch: true,
      call: mockAdapterCall, stream: mockStreamFn, estimateCost: () => 0,
    }))
  })

  test('sanitizes Google API key patterns', async () => {
    mockAdapterCall.mockImplementation(() =>
      Promise.reject(new Error('Invalid key: AIzaSyA1234567890abcdef')),
    )

    try {
      await router.call(
        { model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'hi' }] },
        ctx(),
      )
      expect(true).toBe(false)
    } catch (err: any) {
      expect(err.message).not.toContain('AIzaSyA1234567890abcdef')
      expect(err.message).toContain('AIza***')
    }
  })

  test('preserves non-key content in error messages', async () => {
    mockAdapterCall.mockImplementation(() =>
      Promise.reject(new Error('Rate limit exceeded for model claude-sonnet-4-6')),
    )

    try {
      await router.call(
        { model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'hi' }] },
        ctx(),
      )
      expect(true).toBe(false)
    } catch (err: any) {
      expect(err.message).toContain('Rate limit exceeded')
      expect(err.message).toContain('claude-sonnet-4-6')
    }
  })

  test('passes through already-normalized LLMError', async () => {
    const llmError = Object.assign(new Error('auth failed'), {
      provider: 'anthropic' as LLMProviderName,
      code: 'auth_error' as const,
      retryable: false,
    })
    mockAdapterCall.mockImplementation(() => Promise.reject(llmError))

    try {
      await router.call(
        { model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'hi' }] },
        ctx(),
      )
      expect(true).toBe(false)
    } catch (err: any) {
      expect(err.code).toBe('auth_error')
      expect(err.provider).toBe('anthropic')
    }
  })
})
