/**
 * LLM Integration TEA Tests -- Risk-Based Coverage Expansion
 * Story 3-7: Additional tests generated by TEA (Test Architect)
 *
 * Covers P0/P1 risk gaps not in the main integration test:
 * - Mixed circuit breaker states across providers
 * - AgentRunner max iterations boundary
 * - System prompt + tools full request shape
 * - Circuit breaker half-open failure re-opens circuit
 * - Cost calculation edge cases for all models
 * - AgentRunner with task.context credential scrubbing
 * - BatchCollector empty flush
 * - Fallback order consistency with models.yaml
 *
 * bun test src/__tests__/unit/llm-integration-tea.test.ts
 */
import { describe, it, expect, beforeEach, mock } from 'bun:test'
import type {
  LLMResponse,
  LLMStreamChunk,
  LLMRequest,
  LLMProviderName,
  TaskRequest,
  ToolExecutor,
} from '@corthex/shared'

// =====================================================================
// Mock Setup
// =====================================================================

let anthropicBehavior: 'success' | 'server_error' | 'tool_loop' = 'success'
let anthropicCallCount = 0
let anthropicToolIteration = 0

class MockAnthropicAPIError extends Error {
  status: number
  constructor(status: number, msg: string) {
    super(msg); this.name = 'APIError'; this.status = status
  }
}

mock.module('../../db', () => ({
  db: { insert: () => ({ values: async () => {} }), select: () => ({ from: () => ({ where: () => ({ groupBy: () => ({ orderBy: async () => [] }) }) }) }) },
}))
mock.module('../../db/schema', () => ({ costRecords: {}, agents: {}, departments: {} }))
mock.module('drizzle-orm', () => ({
  sql: () => ({}), and: (...a: unknown[]) => a, eq: () => ({}), gte: () => ({}), lte: () => ({}), sum: () => ({ mapWith: () => ({}) }), count: () => ({}),
}))
mock.module('../../services/credential-vault', () => ({
  getCredentials: async (_: string, p: string) => ({ api_key: `test-${p}`, apiKey: `test-${p}` }),
}))
mock.module('../../services/audit-log', () => ({
  createAuditLog: async () => {}, AUDIT_ACTIONS: { LLM_FALLBACK: 'llm.fallback' },
}))

const MockAnthropic = class {
  messages = {
    create: async (params: Record<string, unknown>) => {
      anthropicCallCount++
      if (anthropicBehavior === 'server_error') throw new MockAnthropicAPIError(500, 'Server error')
      if (anthropicBehavior === 'tool_loop') {
        anthropicToolIteration++
        // Always return tool_use to force max iterations
        return {
          id: `msg-${anthropicToolIteration}`,
          content: [
            { type: 'text', text: `Iteration ${anthropicToolIteration}` },
            { type: 'tool_use', id: `call_${anthropicToolIteration}`, name: 'search', input: { q: 'test' } },
          ],
          model: params.model,
          usage: { input_tokens: 50, output_tokens: 25 },
          stop_reason: 'tool_use',
        }
      }
      return {
        id: 'msg-test',
        content: [{ type: 'text', text: `Response for ${params.model}` }],
        model: params.model,
        usage: { input_tokens: 100, output_tokens: 50 },
        stop_reason: 'end_turn',
      }
    },
    stream: () => ({
      [Symbol.asyncIterator]: async function* () {
        yield { type: 'content_block_delta', delta: { type: 'text_delta', text: 'chunk' } }
        yield { type: 'message_delta', usage: { output_tokens: 10 } }
      },
      finalMessage: async () => ({ usage: { input_tokens: 50, output_tokens: 10 } }),
    }),
  }
}
;(MockAnthropic as unknown as Record<string, unknown>).APIError = MockAnthropicAPIError

mock.module('@anthropic-ai/sdk', () => ({ default: MockAnthropic }))

let openaiCallCount = 0
let openaiBehavior: 'success' | 'server_error' = 'success'

class MockOpenAIAPIError extends Error {
  status: number
  constructor(s: number, m: string) { super(m); this.name = 'APIError'; this.status = s }
}
mock.module('openai', () => ({
  default: class {
    chat = { completions: { create: async (params: Record<string, unknown>) => {
      openaiCallCount++
      if (openaiBehavior === 'server_error') throw new MockOpenAIAPIError(500, 'Server error')
      return {
        id: 'chat-test', choices: [{ message: { content: `OpenAI ${params.model}`, tool_calls: null }, finish_reason: 'stop' }],
        usage: { prompt_tokens: 80, completion_tokens: 40 },
      }
    } } }
    static APIError = MockOpenAIAPIError
  },
}))

let googleBehavior: 'success' | 'server_error' = 'success'
let googleCallCount = 0
mock.module('@google/generative-ai', () => ({
  GoogleGenerativeAI: class {
    getGenerativeModel() {
      return {
        generateContent: async () => {
          googleCallCount++
          if (googleBehavior === 'server_error') throw new Error('500 INTERNAL')
          return { response: { candidates: [{ content: { parts: [{ text: 'Google ok' }] }, finishReason: 'STOP' }], usageMetadata: { promptTokenCount: 60, candidatesTokenCount: 30 } } }
        },
        generateContentStream: async () => ({
          stream: { [Symbol.asyncIterator]: async function* () { yield { text: () => 'g', candidates: null, usageMetadata: { candidatesTokenCount: 5 } } } },
          response: Promise.resolve({ usageMetadata: { promptTokenCount: 30, candidatesTokenCount: 5 } }),
        }),
      }
    }
  },
  GoogleGenerativeAIAbortError: class extends Error {},
  SchemaType: { OBJECT: 'OBJECT', STRING: 'STRING', NUMBER: 'NUMBER', BOOLEAN: 'BOOLEAN', ARRAY: 'ARRAY' },
}))

// =====================================================================
// Imports
// =====================================================================

import { CircuitBreaker } from '../../lib/llm/circuit-breaker'
import { LLMRouter, resolveModel, resolveProvider } from '../../services/llm-router'
import { AgentRunner, buildSystemPrompt, scanForCredentials } from '../../services/agent-runner'
import { BatchCollector } from '../../services/batch-collector'
import { calculateCostMicro } from '../../lib/cost-tracker'
import { getModelConfig, getTierDefaultModel, getFallbackModels, getFallbackOrder, resetModelsCache } from '../../config/models'

// =====================================================================
// Helpers
// =====================================================================

function resetAll() {
  anthropicBehavior = 'success'; anthropicCallCount = 0; anthropicToolIteration = 0
  openaiBehavior = 'success'; openaiCallCount = 0
  googleBehavior = 'success'; googleCallCount = 0
}

const CTX = { companyId: 'tea-company', agentId: 'tea-agent', agentName: 'TEAAgent', source: 'delegation' as const }

// =====================================================================
// Tests
// =====================================================================

describe('TEA: LLM Integration Risk Coverage', () => {
  beforeEach(() => { resetAll(); resetModelsCache() })

  // P0: Mixed circuit breaker states
  describe('P0: Mixed circuit breaker states', () => {
    it('skips open circuit provider and falls back to next available', async () => {
      const cb = new CircuitBreaker(1, 60000)
      cb.recordFailure('anthropic') // Opens anthropic circuit
      // openai still closed, google still closed

      const router = new LLMRouter(cb)
      const resp = await router.call({ model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'test' }] }, CTX)
      // Should skip anthropic, fall to openai
      expect(anthropicCallCount).toBe(0)
      expect(openaiCallCount).toBe(1)
    })

    it('falls back to 3rd provider when 1st and 2nd circuits are open', async () => {
      const cb = new CircuitBreaker(1, 60000)
      cb.recordFailure('anthropic')
      cb.recordFailure('openai')

      const router = new LLMRouter(cb)
      const resp = await router.call({ model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'test' }] }, CTX)
      expect(anthropicCallCount).toBe(0)
      expect(openaiCallCount).toBe(0)
      expect(googleCallCount).toBe(1)
    })

    it('throws when all circuits are open', async () => {
      const cb = new CircuitBreaker(1, 60000)
      cb.recordFailure('anthropic')
      cb.recordFailure('openai')
      cb.recordFailure('google')

      const router = new LLMRouter(cb)
      await expect(router.call({ model: 'claude-sonnet-4-6', messages: [{ role: 'user', content: 'test' }] }, CTX))
        .rejects.toThrow(/All providers failed/)
    })
  })

  // P1: AgentRunner max iterations boundary
  describe('P1: AgentRunner max iterations', () => {
    it('stops at maxToolIterations and appends warning', async () => {
      anthropicBehavior = 'tool_loop'
      const runner = new AgentRunner()
      const agent = {
        id: 'a1', companyId: 'c1', name: 'Looper', tier: 'manager' as const,
        modelName: 'claude-haiku-4-5', soul: 'You loop tools.', allowedTools: ['search'], isActive: true,
      }
      const executor: ToolExecutor = async () => ({ result: 'ok' })
      const task: TaskRequest = { messages: [{ role: 'user', content: 'loop' }], maxToolIterations: 3 }

      const result = await runner.execute(agent, task, CTX, executor)
      expect(result.finishReason).toBe('max_iterations')
      expect(result.content).toContain('Maximum tool iterations reached')
      expect(result.iterations).toBe(3)
      expect(result.toolCalls.length).toBe(3) // 3 iterations of tools
    })

    it('default maxToolIterations is 5', async () => {
      anthropicBehavior = 'tool_loop'
      const runner = new AgentRunner()
      const agent = {
        id: 'a1', companyId: 'c1', name: 'Looper', tier: 'manager' as const,
        modelName: 'claude-haiku-4-5', soul: 'You loop.', allowedTools: ['search'], isActive: true,
      }
      const executor: ToolExecutor = async () => ({ result: 'ok' })
      const task: TaskRequest = { messages: [{ role: 'user', content: 'loop' }] }

      const result = await runner.execute(agent, task, CTX, executor)
      expect(result.iterations).toBe(5)
      expect(result.finishReason).toBe('max_iterations')
    })
  })

  // P1: Circuit breaker half-open failure re-opens
  describe('P1: Circuit breaker half-open failure', () => {
    it('re-opens circuit on failure during half-open state', () => {
      const cb = new CircuitBreaker(1, 10)
      cb.recordFailure('anthropic') // open

      // Wait for cooldown
      const start = Date.now()
      while (Date.now() - start < 15) {}

      expect(cb.isAvailable('anthropic')).toBe(true) // half-open
      cb.recordFailure('anthropic') // fail in half-open -> back to open
      expect(cb.isAvailable('anthropic')).toBe(false) // open again
    })
  })

  // P1: AgentRunner credential scrubbing in task.context
  describe('P1: AgentRunner context credential scrubbing', () => {
    it('rejects task.context containing API key', async () => {
      const runner = new AgentRunner()
      const agent = {
        id: 'a1', companyId: 'c1', name: 'Agent', tier: 'worker' as const,
        modelName: 'claude-haiku-4-5', soul: 'Clean soul.', allowedTools: [], isActive: true,
      }
      const task: TaskRequest = {
        messages: [{ role: 'user', content: 'test' }],
        context: 'Use API key sk-abc123xyz456789012345678',
      }

      await expect(runner.execute(agent, task, CTX)).rejects.toThrow(/Credential pattern/)
    })
  })

  // P1: Full request shape with system prompt + tools
  describe('P1: Full LLM request shape validation', () => {
    it('AgentRunner passes system prompt and tools to LLMRouter', async () => {
      const runner = new AgentRunner()
      const agent = {
        id: 'a1', companyId: 'c1', name: 'FullAgent', tier: 'manager' as const,
        modelName: 'claude-haiku-4-5', soul: 'You are a financial analyst.',
        allowedTools: ['calculator', 'web_search'], isActive: true,
      }
      const task: TaskRequest = {
        messages: [{ role: 'user', content: 'Calculate something' }],
        context: 'Additional context here',
      }

      const result = await runner.execute(agent, task, CTX)
      // Should succeed and return content from anthropic (tier default for manager)
      expect(result.content).toBeDefined()
      expect(result.cost.model).toBe('claude-sonnet-4-6')
    })
  })

  // P1: BatchCollector empty flush
  describe('P1: BatchCollector edge cases', () => {
    it('flush() with no pending items returns empty array', async () => {
      const bc = new BatchCollector()
      const results = await bc.flush('nonexistent-company')
      expect(results).toEqual([])
    })

    it('getStatus() for company with no items returns zeros', () => {
      const bc = new BatchCollector()
      const status = bc.getStatus('empty-company')
      expect(status.pending).toBe(0)
      expect(status.totalItems).toBe(0)
    })
  })

  // P1: Fallback order matches models.yaml
  describe('P1: Fallback order consistency', () => {
    it('getFallbackOrder returns [anthropic, openai, google]', () => {
      const order = getFallbackOrder()
      expect(order).toEqual(['anthropic', 'openai', 'google'])
    })

    it('manager-tier fallback from anthropic includes openai and google equivalents', () => {
      const fallbacks = getFallbackModels('claude-sonnet-4-6')
      const providers = fallbacks.map(m => getModelConfig(m)!.provider)
      expect(providers).toContain('openai')
      expect(providers).toContain('google')
    })

    it('worker-tier fallback from anthropic includes only sub-$1 models', () => {
      const fallbacks = getFallbackModels('claude-haiku-4-5')
      for (const m of fallbacks) {
        const config = getModelConfig(m)!
        expect(config.inputPricePer1M).toBeLessThan(1)
      }
    })
  })

  // P2: Cost calculation across all 6 models
  describe('P2: Cost for every model in catalog', () => {
    const models = [
      { id: 'claude-sonnet-4-6', expectedInput: 3, expectedOutput: 15 },
      { id: 'claude-haiku-4-5', expectedInput: 0.8, expectedOutput: 4 },
      { id: 'gpt-4.1', expectedInput: 2.5, expectedOutput: 10 },
      { id: 'gpt-4.1-mini', expectedInput: 0.4, expectedOutput: 1.6 },
      { id: 'gemini-2.5-pro', expectedInput: 1.25, expectedOutput: 10 },
      { id: 'gemini-2.5-flash', expectedInput: 0.075, expectedOutput: 0.3 },
    ]

    for (const { id, expectedInput, expectedOutput } of models) {
      it(`${id}: cost matches models.yaml pricing`, () => {
        const cost = calculateCostMicro(id, 1_000_000, 1_000_000)
        // cost should be inputPrice + outputPrice (in microdollars for 1M tokens each)
        const expected = Math.round((expectedInput + expectedOutput) * 1_000_000)
        expect(cost).toBe(expected)
      })

      it(`${id}: batch cost is 50% of normal`, () => {
        const normal = calculateCostMicro(id, 10000, 5000)
        const batch = calculateCostMicro(id, 10000, 5000, true)
        expect(batch).toBe(Math.round(normal * 0.5))
      })
    }
  })

  // P2: resolveModel edge cases
  describe('P2: resolveModel edge cases', () => {
    it('empty string modelName uses tier default', () => {
      const result = resolveModel({ tier: 'worker', modelName: '' })
      expect(result.model).toBe('claude-haiku-4-5')
      expect(result.reason).toBe('tier-default')
    })

    it('unknown tier falls back to claude-haiku-4-5', () => {
      const result = resolveModel({ tier: 'unknown' as any, modelName: null })
      expect(result.model).toBe('claude-haiku-4-5')
    })
  })
})
