/**
 * TEA-generated tests for Story 2-4: Org Template Apply API
 * Risk-based coverage: P0 critical paths, P1 important flows, P2 edge cases
 * Generated by TEA (Test Architect) -- bun:test framework
 */
import { describe, expect, test } from 'bun:test'
import * as orgService from '../../services/organization'
import { AUDIT_ACTIONS } from '../../services/audit-log'
import {
  INVESTMENT_TEMPLATE,
  MARKETING_TEMPLATE,
  ALL_IN_ONE_TEMPLATE,
  BUILTIN_TEMPLATES,
} from '../../services/seed.service'
import type { TemplateData, TemplateDepartment, TemplateAgent } from '../../services/seed.service'

// ============================================================
// P0: Critical Path Tests -- Core API Functions Exist & Export
// ============================================================
describe('[P0] Core API functions export correctly', () => {
  test('applyTemplate is exported as async function', () => {
    expect(typeof orgService.applyTemplate).toBe('function')
    const result = orgService.applyTemplate(
      { companyId: 'test', userId: 'test', isAdminUser: true },
      'test-id',
    )
    expect(result).toBeInstanceOf(Promise)
  })

  test('getOrgTemplates is exported as async function', () => {
    expect(typeof orgService.getOrgTemplates).toBe('function')
    expect(orgService.getOrgTemplates('test')).toBeInstanceOf(Promise)
  })

  test('getOrgTemplateById is exported as async function', () => {
    expect(typeof orgService.getOrgTemplateById).toBe('function')
    expect(orgService.getOrgTemplateById('test', 'test')).toBeInstanceOf(Promise)
  })

  test('TemplateApplySummary type has all required fields', () => {
    const summary: orgService.TemplateApplySummary = {
      templateId: 'id',
      templateName: 'name',
      departmentsCreated: 1,
      departmentsSkipped: 2,
      agentsCreated: 3,
      agentsSkipped: 4,
      details: [{
        departmentName: 'dept',
        action: 'created',
        departmentId: 'uuid',
        agentsCreated: ['a1'],
        agentsSkipped: ['a2'],
      }],
    }
    expect(summary.departmentsCreated).toBe(1)
    expect(summary.departmentsSkipped).toBe(2)
    expect(summary.agentsCreated).toBe(3)
    expect(summary.agentsSkipped).toBe(4)
    expect(summary.details).toHaveLength(1)
    expect(summary.details[0].agentsCreated).toContain('a1')
    expect(summary.details[0].agentsSkipped).toContain('a2')
  })
})

// ============================================================
// P0: Critical Path Tests -- Audit Action
// ============================================================
describe('[P0] Audit action constant', () => {
  test('ORG_TEMPLATE_APPLY is defined correctly', () => {
    expect(AUDIT_ACTIONS.ORG_TEMPLATE_APPLY).toBe('org.template.apply')
  })

  test('no regression on existing audit actions', () => {
    expect(AUDIT_ACTIONS.ORG_DEPARTMENT_CREATE).toBeDefined()
    expect(AUDIT_ACTIONS.ORG_DEPARTMENT_UPDATE).toBeDefined()
    expect(AUDIT_ACTIONS.ORG_DEPARTMENT_DELETE).toBeDefined()
    expect(AUDIT_ACTIONS.ORG_AGENT_CREATE).toBeDefined()
    expect(AUDIT_ACTIONS.ORG_AGENT_UPDATE).toBeDefined()
    expect(AUDIT_ACTIONS.ORG_AGENT_DEACTIVATE).toBeDefined()
    expect(AUDIT_ACTIONS.ORG_CASCADE_ANALYZE).toBeDefined()
    expect(AUDIT_ACTIONS.ORG_CASCADE_EXECUTE).toBeDefined()
  })
})

// ============================================================
// P0: Template Data Integrity
// ============================================================
describe('[P0] Template data integrity', () => {
  test('investment template: 1 dept, 5 agents, correct tiers', () => {
    expect(INVESTMENT_TEMPLATE.departments).toHaveLength(1)
    const dept = INVESTMENT_TEMPLATE.departments[0]
    expect(dept.name).toBe('재무팀')
    expect(dept.agents).toHaveLength(5)
    expect(dept.agents.filter(a => a.tier === 'manager')).toHaveLength(1)
    expect(dept.agents.filter(a => a.tier === 'specialist')).toHaveLength(2)
    expect(dept.agents.filter(a => a.tier === 'worker')).toHaveLength(2)
  })

  test('marketing template: 1 dept, 4 agents, correct tiers', () => {
    expect(MARKETING_TEMPLATE.departments).toHaveLength(1)
    const dept = MARKETING_TEMPLATE.departments[0]
    expect(dept.name).toBe('마케팅팀')
    expect(dept.agents).toHaveLength(4)
    expect(dept.agents.filter(a => a.tier === 'manager')).toHaveLength(1)
  })

  test('all-in-one template: 4 depts, 12 agents total', () => {
    expect(ALL_IN_ONE_TEMPLATE.departments).toHaveLength(4)
    const total = ALL_IN_ONE_TEMPLATE.departments.reduce((s, d) => s + d.agents.length, 0)
    expect(total).toBe(12)
  })

  test('3 builtin templates exist', () => {
    expect(BUILTIN_TEMPLATES).toHaveLength(3)
    expect(BUILTIN_TEMPLATES.map(t => t.name)).toEqual(['투자분석', '마케팅', '올인원'])
  })
})

// ============================================================
// P0: Merge Strategy Logic (Pure Unit Tests)
// ============================================================
describe('[P0] Merge strategy -- department name deduplication', () => {
  test('skip department when name already exists', () => {
    const existing = new Set(['재무팀'])
    const template = INVESTMENT_TEMPLATE
    let created = 0, skipped = 0
    for (const dept of template.departments) {
      if (existing.has(dept.name)) skipped++
      else created++
    }
    expect(skipped).toBe(1)
    expect(created).toBe(0)
  })

  test('create department when name does not exist', () => {
    const existing = new Set(['인사팀'])
    const template = INVESTMENT_TEMPLATE
    let created = 0, skipped = 0
    for (const dept of template.departments) {
      if (existing.has(dept.name)) skipped++
      else created++
    }
    expect(created).toBe(1)
    expect(skipped).toBe(0)
  })

  test('all-in-one: partial overlap creates only missing depts', () => {
    const existing = new Set(['개발팀', '재무팀'])
    const template = ALL_IN_ONE_TEMPLATE
    let created = 0, skipped = 0
    for (const dept of template.departments) {
      if (existing.has(dept.name)) skipped++
      else created++
    }
    expect(skipped).toBe(2) // 개발팀, 재무팀
    expect(created).toBe(2) // 경영지원실, 마케팅팀
  })
})

describe('[P0] Merge strategy -- agent name deduplication', () => {
  test('skip agent when name already exists in company', () => {
    const existingAgents = new Set(['CIO', '투자분석 전문가 A'])
    const agents = INVESTMENT_TEMPLATE.departments[0].agents
    let created = 0, skipped = 0
    for (const a of agents) {
      if (existingAgents.has(a.name)) skipped++
      else created++
    }
    expect(skipped).toBe(2)
    expect(created).toBe(3)
  })

  test('create all agents when none exist', () => {
    const existingAgents = new Set<string>()
    const agents = MARKETING_TEMPLATE.departments[0].agents
    let created = 0
    for (const a of agents) {
      if (!existingAgents.has(a.name)) created++
    }
    expect(created).toBe(4)
  })

  test('skip all agents when all names exist', () => {
    const names = INVESTMENT_TEMPLATE.departments[0].agents.map(a => a.name)
    const existingAgents = new Set(names)
    let skipped = 0
    for (const a of INVESTMENT_TEMPLATE.departments[0].agents) {
      if (existingAgents.has(a.name)) skipped++
    }
    expect(skipped).toBe(5)
  })
})

// ============================================================
// P1: Combined Merge Simulation
// ============================================================
describe('[P1] Full merge simulation', () => {
  test('apply marketing template to company with existing CMO agent', () => {
    const existingDepts = new Set<string>()
    const existingAgents = new Set(['CMO'])
    const template = MARKETING_TEMPLATE
    let dc = 0, ds = 0, ac = 0, as2 = 0
    for (const dept of template.departments) {
      if (existingDepts.has(dept.name)) ds++
      else dc++
      for (const a of dept.agents) {
        if (existingAgents.has(a.name)) as2++
        else ac++
      }
    }
    expect(dc).toBe(1)
    expect(ds).toBe(0)
    expect(ac).toBe(3) // 콘텐츠 전문가, SNS 전문가, 디자인 워커
    expect(as2).toBe(1) // CMO
  })

  test('apply all-in-one to fully populated company', () => {
    const template = ALL_IN_ONE_TEMPLATE
    const allDeptNames = new Set(template.departments.map(d => d.name))
    const allAgentNames = new Set(template.departments.flatMap(d => d.agents.map(a => a.name)))

    let dc = 0, ds = 0, ac = 0, as2 = 0
    for (const dept of template.departments) {
      if (allDeptNames.has(dept.name)) ds++
      else dc++
      for (const a of dept.agents) {
        if (allAgentNames.has(a.name)) as2++
        else ac++
      }
    }
    expect(dc).toBe(0)
    expect(ds).toBe(4)
    expect(ac).toBe(0)
    expect(as2).toBe(12)
  })

  test('department skipped but agents still created under it', () => {
    // Scenario: 재무팀 exists but none of its agents do
    const existingDepts = new Map([['재무팀', 'existing-dept-id']])
    const existingAgents = new Set<string>()
    const template = INVESTMENT_TEMPLATE

    const details: Array<{ dept: string; action: string; agentsCreated: number }> = []
    for (const dept of template.departments) {
      const deptAction = existingDepts.has(dept.name) ? 'skipped' : 'created'
      let agentsCreated = 0
      for (const a of dept.agents) {
        if (!existingAgents.has(a.name)) agentsCreated++
      }
      details.push({ dept: dept.name, action: deptAction, agentsCreated })
    }

    expect(details[0].action).toBe('skipped')
    expect(details[0].agentsCreated).toBe(5) // All 5 agents created under existing dept
  })
})

// ============================================================
// P1: Template Data Quality
// ============================================================
describe('[P1] Template agent data completeness', () => {
  const allTemplates = [INVESTMENT_TEMPLATE, MARKETING_TEMPLATE, ALL_IN_ONE_TEMPLATE]

  test('all agents have non-empty name', () => {
    for (const tmpl of allTemplates) {
      for (const dept of tmpl.departments) {
        for (const agent of dept.agents) {
          expect(agent.name.length).toBeGreaterThan(0)
        }
      }
    }
  })

  test('all agents have valid tier', () => {
    const validTiers = ['manager', 'specialist', 'worker']
    for (const tmpl of allTemplates) {
      for (const dept of tmpl.departments) {
        for (const agent of dept.agents) {
          expect(validTiers).toContain(agent.tier)
        }
      }
    }
  })

  test('all agents have valid modelName', () => {
    const validModels = ['claude-sonnet-4-6', 'claude-haiku-4-5']
    for (const tmpl of allTemplates) {
      for (const dept of tmpl.departments) {
        for (const agent of dept.agents) {
          expect(validModels).toContain(agent.modelName)
        }
      }
    }
  })

  test('managers always use sonnet model', () => {
    for (const tmpl of allTemplates) {
      for (const dept of tmpl.departments) {
        for (const agent of dept.agents) {
          if (agent.tier === 'manager') {
            expect(agent.modelName).toBe('claude-sonnet-4-6')
          }
        }
      }
    }
  })

  test('non-managers use haiku model', () => {
    for (const tmpl of allTemplates) {
      for (const dept of tmpl.departments) {
        for (const agent of dept.agents) {
          if (agent.tier !== 'manager') {
            expect(agent.modelName).toBe('claude-haiku-4-5')
          }
        }
      }
    }
  })

  test('all agents have non-empty soul with Korean text', () => {
    for (const tmpl of allTemplates) {
      for (const dept of tmpl.departments) {
        for (const agent of dept.agents) {
          expect(agent.soul.length).toBeGreaterThan(10)
          expect(agent.soul).toMatch(/[\uAC00-\uD7A3]/)
        }
      }
    }
  })

  test('all agents have at least one allowed tool', () => {
    for (const tmpl of allTemplates) {
      for (const dept of tmpl.departments) {
        for (const agent of dept.agents) {
          expect(agent.allowedTools.length).toBeGreaterThan(0)
        }
      }
    }
  })

  test('all agents have non-empty role', () => {
    for (const tmpl of allTemplates) {
      for (const dept of tmpl.departments) {
        for (const agent of dept.agents) {
          expect(agent.role.length).toBeGreaterThan(0)
        }
      }
    }
  })

  test('all departments have non-empty description', () => {
    for (const tmpl of allTemplates) {
      for (const dept of tmpl.departments) {
        expect(dept.description.length).toBeGreaterThan(0)
      }
    }
  })
})

// ============================================================
// P1: Template-specific Content Validation
// ============================================================
describe('[P1] Investment template content', () => {
  const dept = INVESTMENT_TEMPLATE.departments[0]

  test('CIO has finance tools', () => {
    const cio = dept.agents.find(a => a.name === 'CIO')!
    expect(cio.allowedTools).toContain('get_stock_price')
    expect(cio.allowedTools).toContain('get_account_balance')
    expect(cio.allowedTools).toContain('place_stock_order')
  })

  test('CIO is manager tier', () => {
    const cio = dept.agents.find(a => a.name === 'CIO')!
    expect(cio.tier).toBe('manager')
  })

  test('all agents have nameEn', () => {
    for (const agent of dept.agents) {
      expect(agent.nameEn).toBeTruthy()
    }
  })

  test('workers have research-specific tools', () => {
    const workers = dept.agents.filter(a => a.tier === 'worker')
    for (const w of workers) {
      expect(w.allowedTools).toContain('search_web')
    }
  })
})

describe('[P1] Marketing template content', () => {
  const dept = MARKETING_TEMPLATE.departments[0]

  test('CMO has instagram tools', () => {
    const cmo = dept.agents.find(a => a.name === 'CMO')!
    expect(cmo.allowedTools).toContain('publish_instagram')
    expect(cmo.allowedTools).toContain('get_instagram_insights')
  })

  test('SNS 전문가 has social media tools', () => {
    const sns = dept.agents.find(a => a.name === 'SNS 전문가')!
    expect(sns.allowedTools).toContain('publish_instagram')
  })

  test('디자인 워커 has image tools', () => {
    const designer = dept.agents.find(a => a.name === '디자인 워커')!
    expect(designer.allowedTools).toContain('generate_image')
  })
})

describe('[P1] All-in-one template content', () => {
  test('has all 4 department names', () => {
    const names = ALL_IN_ONE_TEMPLATE.departments.map(d => d.name)
    expect(names).toEqual(['경영지원실', '개발팀', '마케팅팀', '재무팀'])
  })

  test('each department has exactly 3 agents', () => {
    for (const dept of ALL_IN_ONE_TEMPLATE.departments) {
      expect(dept.agents).toHaveLength(3)
    }
  })

  test('each department has exactly 1 manager', () => {
    for (const dept of ALL_IN_ONE_TEMPLATE.departments) {
      const managers = dept.agents.filter(a => a.tier === 'manager')
      expect(managers).toHaveLength(1)
    }
  })

  test('COO has calendar and email tools', () => {
    const mgmt = ALL_IN_ONE_TEMPLATE.departments.find(d => d.name === '경영지원실')!
    const coo = mgmt.agents.find(a => a.name === 'COO')!
    expect(coo.allowedTools).toContain('send_email')
    expect(coo.allowedTools).toContain('list_calendar_events')
    expect(coo.allowedTools).toContain('create_calendar_event')
  })

  test('CFO has stock price tools', () => {
    const finance = ALL_IN_ONE_TEMPLATE.departments.find(d => d.name === '재무팀')!
    const cfo = finance.agents.find(a => a.name === 'CFO')!
    expect(cfo.allowedTools).toContain('get_stock_price')
    expect(cfo.allowedTools).toContain('get_account_balance')
  })
})

// ============================================================
// P1: Service Function No-Regression
// ============================================================
describe('[P1] Service function exports -- no regression', () => {
  test('all existing organization service functions still exported', () => {
    const expectedExports = [
      'getDepartments', 'getDepartmentById', 'createDepartment', 'updateDepartment', 'deleteDepartment',
      'getAgents', 'getAgentById', 'createAgent', 'updateAgent', 'deactivateAgent',
      'analyzeCascade', 'executeCascade',
      'getOrgTemplates', 'getOrgTemplateById', 'applyTemplate',
    ]
    for (const name of expectedExports) {
      expect(typeof (orgService as Record<string, unknown>)[name]).toBe('function')
    }
  })
})

// ============================================================
// P2: Edge Cases
// ============================================================
describe('[P2] Edge cases -- template data serialization', () => {
  test('JSON round-trip preserves investment template', () => {
    const json = JSON.stringify(INVESTMENT_TEMPLATE)
    const parsed = JSON.parse(json) as TemplateData
    expect(parsed.departments).toHaveLength(1)
    expect(parsed.departments[0].agents).toHaveLength(5)
    expect(parsed.departments[0].agents[0].name).toBe(INVESTMENT_TEMPLATE.departments[0].agents[0].name)
  })

  test('JSON round-trip preserves all-in-one template', () => {
    const json = JSON.stringify(ALL_IN_ONE_TEMPLATE)
    const parsed = JSON.parse(json) as TemplateData
    expect(parsed.departments).toHaveLength(4)
    const totalAgents = parsed.departments.reduce((s, d) => s + d.agents.length, 0)
    expect(totalAgents).toBe(12)
  })

  test('template data handles special characters in soul', () => {
    for (const tmpl of [INVESTMENT_TEMPLATE, MARKETING_TEMPLATE, ALL_IN_ONE_TEMPLATE]) {
      for (const dept of tmpl.departments) {
        for (const agent of dept.agents) {
          // Ensure soul can be JSON serialized and deserialized
          const json = JSON.stringify({ soul: agent.soul })
          const parsed = JSON.parse(json)
          expect(parsed.soul).toBe(agent.soul)
        }
      }
    }
  })
})

describe('[P2] Edge cases -- empty and boundary conditions', () => {
  test('empty existing sets mean full creation', () => {
    const existingDepts = new Set<string>()
    const existingAgents = new Set<string>()
    const template = ALL_IN_ONE_TEMPLATE

    let totalCreated = 0
    for (const dept of template.departments) {
      if (!existingDepts.has(dept.name)) totalCreated++
      for (const a of dept.agents) {
        if (!existingAgents.has(a.name)) totalCreated++
      }
    }
    expect(totalCreated).toBe(16) // 4 depts + 12 agents
  })

  test('summary detail action field values are valid', () => {
    const validActions: Array<'created' | 'skipped'> = ['created', 'skipped']
    const detail: orgService.TemplateApplySummary['details'][number] = {
      departmentName: 'test',
      action: 'created',
      departmentId: 'id',
      agentsCreated: [],
      agentsSkipped: [],
    }
    expect(validActions).toContain(detail.action)

    detail.action = 'skipped'
    expect(validActions).toContain(detail.action)
  })

  test('template with duplicate agent names across departments', () => {
    // All-in-one has CMO in 마케팅팀 -- check uniqueness tracking
    const allNames = ALL_IN_ONE_TEMPLATE.departments.flatMap(d => d.agents.map(a => a.name))
    const uniqueNames = new Set(allNames)
    // CMO appears in 마케팅팀
    // Check if any name is duplicated across departments
    const hasDupes = allNames.length !== uniqueNames.size
    // This is valid -- the merge strategy handles it by tracking globally
    if (hasDupes) {
      expect(allNames.length).toBeGreaterThan(uniqueNames.size)
    } else {
      expect(allNames.length).toBe(uniqueNames.size)
    }
  })
})

// ============================================================
// P2: Performance bounds
// ============================================================
describe('[P2] NFR35 -- performance bounds', () => {
  test('largest template operations count is manageable', () => {
    const ops = ALL_IN_ONE_TEMPLATE.departments.length +
      ALL_IN_ONE_TEMPLATE.departments.reduce((s, d) => s + d.agents.length, 0)
    expect(ops).toBe(16) // 4 + 12
    expect(ops).toBeLessThan(100) // Well within 2-minute budget
  })

  test('template data is reasonably sized for JSONB storage', () => {
    const jsonSize = JSON.stringify(ALL_IN_ONE_TEMPLATE).length
    expect(jsonSize).toBeLessThan(50000) // Under 50KB
    expect(jsonSize).toBeGreaterThan(1000) // Not trivially small
  })
})

// ============================================================
// P2: Interface contracts
// ============================================================
describe('[P2] Type interface contracts', () => {
  test('TemplateAgent optional nameEn field', () => {
    const withEn: TemplateAgent = {
      name: 'Test', nameEn: 'TestEn', role: 'r', tier: 'worker',
      modelName: 'claude-haiku-4-5', soul: 's', allowedTools: ['t'],
    }
    expect(withEn.nameEn).toBe('TestEn')

    const withoutEn: TemplateAgent = {
      name: 'Test', role: 'r', tier: 'specialist',
      modelName: 'claude-haiku-4-5', soul: 's', allowedTools: [],
    }
    expect(withoutEn.nameEn).toBeUndefined()
  })

  test('TemplateDepartment requires name, description, agents', () => {
    const dept: TemplateDepartment = {
      name: 'Test Dept', description: 'Desc', agents: [],
    }
    expect(dept.name).toBe('Test Dept')
    expect(dept.agents).toHaveLength(0)
  })

  test('TemplateData requires departments array', () => {
    const empty: TemplateData = { departments: [] }
    expect(empty.departments).toHaveLength(0)

    const withDepts: TemplateData = {
      departments: [{ name: 'd', description: 'dd', agents: [] }],
    }
    expect(withDepts.departments).toHaveLength(1)
  })
})
