/**
 * QA-generated tests for Story 2-4: Org Template Apply API
 * Focus: functional verification, error handling, edge cases
 * Generated by Quinn QA -- bun:test framework
 */
import { describe, expect, test } from 'bun:test'
import * as orgService from '../../services/organization'
import { AUDIT_ACTIONS } from '../../services/audit-log'
import {
  INVESTMENT_TEMPLATE,
  MARKETING_TEMPLATE,
  ALL_IN_ONE_TEMPLATE,
  BUILTIN_TEMPLATES,
} from '../../services/seed.service'
import type { TemplateData } from '../../services/seed.service'

// ============================================================
// QA-1: API Function Signatures & Return Types
// ============================================================
describe('QA: API function signatures', () => {
  test('applyTemplate requires exactly 2 parameters', () => {
    expect(orgService.applyTemplate.length).toBe(2)
  })

  test('getOrgTemplates requires exactly 1 parameter', () => {
    expect(orgService.getOrgTemplates.length).toBe(1)
  })

  test('getOrgTemplateById requires exactly 2 parameters', () => {
    expect(orgService.getOrgTemplateById.length).toBe(2)
  })

  test('applyTemplate returns Promise (async function)', () => {
    const result = orgService.applyTemplate(
      { companyId: 'qa-test', userId: 'qa-user', isAdminUser: true },
      'nonexistent-template',
    )
    expect(result).toBeInstanceOf(Promise)
  })
})

// ============================================================
// QA-2: Error Code Convention
// ============================================================
describe('QA: Error code conventions', () => {
  test('TMPL_001 follows project error code pattern (prefix_NNN)', () => {
    expect('TMPL_001').toMatch(/^[A-Z]+_\d{3}$/)
  })

  test('TMPL_002 follows project error code pattern', () => {
    expect('TMPL_002').toMatch(/^[A-Z]+_\d{3}$/)
  })

  test('error codes are distinct', () => {
    const codes = ['TMPL_001', 'TMPL_002']
    const unique = new Set(codes)
    expect(unique.size).toBe(codes.length)
  })

  test('error codes do not conflict with existing DEPT/AGENT codes', () => {
    const existingPrefixes = ['DEPT', 'AGENT', 'CASCADE']
    expect(existingPrefixes).not.toContain('TMPL')
  })
})

// ============================================================
// QA-3: Merge Strategy Boundary Conditions
// ============================================================
describe('QA: Merge boundary conditions', () => {
  test('case-sensitive department name matching', () => {
    // "재무팀" vs "재무팀 " (with trailing space) should NOT match
    const existing = new Set(['재무팀'])
    expect(existing.has('재무팀')).toBe(true)
    expect(existing.has('재무팀 ')).toBe(false)
    expect(existing.has(' 재무팀')).toBe(false)
  })

  test('case-sensitive agent name matching', () => {
    const existing = new Set(['CIO'])
    expect(existing.has('CIO')).toBe(true)
    expect(existing.has('cio')).toBe(false)
    expect(existing.has('Cio')).toBe(false)
  })

  test('empty template produces zero-sum summary', () => {
    const emptyTemplate: TemplateData = { departments: [] }
    let dc = 0, ds = 0, ac = 0, as2 = 0
    for (const dept of emptyTemplate.departments) {
      dc++
      for (const a of dept.agents) {
        ac++
      }
    }
    expect(dc).toBe(0)
    expect(ds).toBe(0)
    expect(ac).toBe(0)
    expect(as2).toBe(0)
  })

  test('department with empty agents array is valid', () => {
    const template: TemplateData = {
      departments: [{ name: '빈부서', description: '에이전트 없음', agents: [] }],
    }
    let dc = 0, ac = 0
    const existing = new Set<string>()
    for (const dept of template.departments) {
      if (!existing.has(dept.name)) dc++
      for (const a of dept.agents) { ac++ }
    }
    expect(dc).toBe(1)
    expect(ac).toBe(0)
  })
})

// ============================================================
// QA-4: Template Data Cross-validation
// ============================================================
describe('QA: Template data cross-validation', () => {
  test('no agent appears in more than one department within same template', () => {
    for (const tmpl of [INVESTMENT_TEMPLATE, MARKETING_TEMPLATE]) {
      const allNames: string[] = []
      for (const dept of tmpl.departments) {
        for (const agent of dept.agents) {
          allNames.push(agent.name)
        }
      }
      const unique = new Set(allNames)
      expect(allNames.length).toBe(unique.size)
    }
  })

  test('all-in-one template may have shared agent names across depts', () => {
    const allNames = ALL_IN_ONE_TEMPLATE.departments.flatMap(d => d.agents.map(a => a.name))
    const unique = new Set(allNames)
    // This is informational -- the merge strategy handles it correctly
    // by tracking agent names globally across the company
    expect(allNames.length).toBeGreaterThanOrEqual(unique.size)
  })

  test('no department name is duplicated within same template', () => {
    for (const tmpl of [INVESTMENT_TEMPLATE, MARKETING_TEMPLATE, ALL_IN_ONE_TEMPLATE]) {
      const names = tmpl.departments.map(d => d.name)
      const unique = new Set(names)
      expect(names.length).toBe(unique.size)
    }
  })

  test('builtin template descriptions are unique', () => {
    const descriptions = BUILTIN_TEMPLATES.map(t => t.description)
    const unique = new Set(descriptions)
    expect(descriptions.length).toBe(unique.size)
  })

  test('builtin template names are unique', () => {
    const names = BUILTIN_TEMPLATES.map(t => t.name)
    const unique = new Set(names)
    expect(names.length).toBe(unique.size)
  })
})

// ============================================================
// QA-5: Summary Structure Validation
// ============================================================
describe('QA: TemplateApplySummary structure', () => {
  test('summary counts are non-negative integers', () => {
    const summary: orgService.TemplateApplySummary = {
      templateId: 'id',
      templateName: 'n',
      departmentsCreated: 0,
      departmentsSkipped: 0,
      agentsCreated: 0,
      agentsSkipped: 0,
      details: [],
    }
    expect(summary.departmentsCreated).toBeGreaterThanOrEqual(0)
    expect(summary.departmentsSkipped).toBeGreaterThanOrEqual(0)
    expect(summary.agentsCreated).toBeGreaterThanOrEqual(0)
    expect(summary.agentsSkipped).toBeGreaterThanOrEqual(0)
    expect(Number.isInteger(summary.departmentsCreated)).toBe(true)
  })

  test('details array matches department count', () => {
    // When applying a template, details should have one entry per template department
    const template = ALL_IN_ONE_TEMPLATE
    const expectedDetailCount = template.departments.length
    expect(expectedDetailCount).toBe(4)
  })

  test('detail agentsCreated + agentsSkipped = template agents for dept', () => {
    const template = INVESTMENT_TEMPLATE
    const dept = template.departments[0]
    const existingAgents = new Set(['CIO'])

    let created = 0, skipped = 0
    for (const agent of dept.agents) {
      if (existingAgents.has(agent.name)) skipped++
      else created++
    }
    expect(created + skipped).toBe(dept.agents.length)
  })

  test('departmentsCreated + departmentsSkipped = template dept count', () => {
    const template = ALL_IN_ONE_TEMPLATE
    const existingDepts = new Set(['마케팅팀'])
    let created = 0, skipped = 0
    for (const dept of template.departments) {
      if (existingDepts.has(dept.name)) skipped++
      else created++
    }
    expect(created + skipped).toBe(template.departments.length)
  })
})

// ============================================================
// QA-6: Audit Action Completeness
// ============================================================
describe('QA: Audit action for template apply', () => {
  test('ORG_TEMPLATE_APPLY value follows naming convention', () => {
    expect(AUDIT_ACTIONS.ORG_TEMPLATE_APPLY).toMatch(/^org\.template\.\w+$/)
  })

  test('audit action value is a dot-separated string', () => {
    const parts = AUDIT_ACTIONS.ORG_TEMPLATE_APPLY.split('.')
    expect(parts.length).toBe(3)
    expect(parts[0]).toBe('org')
    expect(parts[1]).toBe('template')
    expect(parts[2]).toBe('apply')
  })
})

// ============================================================
// QA-7: Regression -- Existing Service Functions
// ============================================================
describe('QA: No regression on existing exports', () => {
  const functions = [
    'getDepartments', 'getDepartmentById', 'createDepartment',
    'updateDepartment', 'deleteDepartment',
    'getAgents', 'getAgentById', 'createAgent',
    'updateAgent', 'deactivateAgent',
    'analyzeCascade', 'executeCascade',
  ]

  for (const fn of functions) {
    test(`${fn} is still exported`, () => {
      expect(typeof (orgService as Record<string, unknown>)[fn]).toBe('function')
    })
  }
})

// ============================================================
// QA-8: Template Agent Field Validation (Deeper)
// ============================================================
describe('QA: Agent field validation -- deeper checks', () => {
  test('agent names are not empty strings', () => {
    for (const tmpl of [INVESTMENT_TEMPLATE, MARKETING_TEMPLATE, ALL_IN_ONE_TEMPLATE]) {
      for (const dept of tmpl.departments) {
        for (const agent of dept.agents) {
          expect(agent.name.trim().length).toBeGreaterThan(0)
        }
      }
    }
  })

  test('agent roles are not empty strings', () => {
    for (const tmpl of [INVESTMENT_TEMPLATE, MARKETING_TEMPLATE, ALL_IN_ONE_TEMPLATE]) {
      for (const dept of tmpl.departments) {
        for (const agent of dept.agents) {
          expect(agent.role.trim().length).toBeGreaterThan(0)
        }
      }
    }
  })

  test('allowedTools arrays contain only strings', () => {
    for (const tmpl of [INVESTMENT_TEMPLATE, MARKETING_TEMPLATE, ALL_IN_ONE_TEMPLATE]) {
      for (const dept of tmpl.departments) {
        for (const agent of dept.agents) {
          for (const tool of agent.allowedTools) {
            expect(typeof tool).toBe('string')
            expect(tool.length).toBeGreaterThan(0)
          }
        }
      }
    }
  })

  test('modelName values are valid Claude model identifiers', () => {
    const validModels = new Set(['claude-sonnet-4-6', 'claude-haiku-4-5'])
    for (const tmpl of [INVESTMENT_TEMPLATE, MARKETING_TEMPLATE, ALL_IN_ONE_TEMPLATE]) {
      for (const dept of tmpl.departments) {
        for (const agent of dept.agents) {
          expect(validModels.has(agent.modelName)).toBe(true)
        }
      }
    }
  })

  test('soul strings contain markdown headings', () => {
    for (const tmpl of [INVESTMENT_TEMPLATE, MARKETING_TEMPLATE, ALL_IN_ONE_TEMPLATE]) {
      for (const dept of tmpl.departments) {
        for (const agent of dept.agents) {
          expect(agent.soul).toContain('#')
        }
      }
    }
  })
})

// ============================================================
// QA-9: Performance Sanity
// ============================================================
describe('QA: Performance sanity checks', () => {
  test('total operations for all-in-one < 50', () => {
    const ops = ALL_IN_ONE_TEMPLATE.departments.length +
      ALL_IN_ONE_TEMPLATE.departments.reduce((s, d) => s + d.agents.length, 0)
    expect(ops).toBeLessThan(50)
  })

  test('JSONB data size reasonable for all templates', () => {
    for (const tmpl of [INVESTMENT_TEMPLATE, MARKETING_TEMPLATE, ALL_IN_ONE_TEMPLATE]) {
      const size = JSON.stringify(tmpl).length
      expect(size).toBeLessThan(100000) // < 100KB each
    }
  })
})
