/**
 * Provider Fallback Strategy -- TEA Risk-Based Tests
 * Story 3-3: Edge cases, boundary conditions, concurrent behavior
 *
 * Generated by TEA (Test Architect) automate workflow.
 * Focus: high-risk paths not covered by dev-story tests.
 *
 * bun test src/__tests__/unit/provider-fallback-tea.test.ts
 */
import { describe, test, expect, mock, beforeEach } from 'bun:test'
import type { LLMRequest, LLMResponse, LLMStreamChunk, LLMProviderName } from '@corthex/shared'

// === Mock modules BEFORE imports ===

const mockGetCredentials = mock(() =>
  Promise.resolve({ api_key: 'test-api-key-123' }),
)
const mockRecordCost = mock(() => Promise.resolve())
const mockCreateAuditLog = mock(() => Promise.resolve({ id: 'audit-1' }))

const mockAdapterCall = mock((): Promise<LLMResponse> =>
  Promise.resolve({
    content: 'Hello',
    toolCalls: [],
    usage: { inputTokens: 100, outputTokens: 50 },
    model: 'claude-sonnet-4-6',
    provider: 'anthropic' as LLMProviderName,
    finishReason: 'stop' as const,
  }),
)

const mockAdapterStream = mock(function* (): Generator<LLMStreamChunk> {
  yield { type: 'text', content: 'Hello' }
  yield { type: 'done', usage: { inputTokens: 80, outputTokens: 40 } }
})

const mockCreateProvider = mock(() => ({
  name: 'anthropic' as LLMProviderName,
  supportsBatch: true,
  call: mockAdapterCall,
  stream: mockAdapterStream,
  estimateCost: () => 0.001,
}))

mock.module('../../services/credential-vault', () => ({
  getCredentials: mockGetCredentials,
}))
mock.module('../../lib/cost-tracker', () => ({
  recordCost: mockRecordCost,
}))
mock.module('../../lib/llm/index', () => ({
  createProvider: mockCreateProvider,
}))
mock.module('../../services/audit-log', () => ({
  createAuditLog: mockCreateAuditLog,
  AUDIT_ACTIONS: { LLM_FALLBACK: 'llm.fallback' },
}))

import { CircuitBreaker } from '../../lib/llm/circuit-breaker'
import { LLMRouter } from '../../services/llm-router'
import { getFallbackModels, getModelConfig } from '../../config/models'

// === Helpers ===

function makeRequest(model = 'claude-sonnet-4-6'): LLMRequest {
  return { model, messages: [{ role: 'user', content: 'Test' }] }
}

const ctx = {
  companyId: 'company-tea',
  agentId: 'agent-tea',
  agentName: 'TEA-Agent',
  sessionId: 'session-tea',
  source: 'chat' as const,
}

function makeErr(code: string, provider: LLMProviderName = 'anthropic'): any {
  const e = new Error(`${provider} ${code}`) as any
  e.code = code
  e.provider = provider
  e.retryable = ['server_error', 'timeout', 'rate_limit'].includes(code)
  return e
}

function makeResp(model: string, provider: LLMProviderName): LLMResponse {
  return {
    content: `OK from ${provider}`,
    toolCalls: [],
    usage: { inputTokens: 50, outputTokens: 25 },
    model,
    provider,
    finishReason: 'stop',
  }
}

// =====================================================
// TEA: CIRCUIT BREAKER EDGE CASES
// =====================================================

describe('TEA: CircuitBreaker edge cases', () => {
  test('exactly at threshold: 2 failures is not open', () => {
    const cb = new CircuitBreaker(3, 60_000)
    cb.recordFailure('anthropic')
    cb.recordFailure('anthropic')
    expect(cb.isAvailable('anthropic')).toBe(true)
    expect(cb.getStatus().anthropic.state).toBe('closed')
    expect(cb.getStatus().anthropic.consecutiveFailures).toBe(2)
  })

  test('interleaved success resets counter mid-sequence', () => {
    const cb = new CircuitBreaker(3, 60_000)
    cb.recordFailure('openai')
    cb.recordFailure('openai')
    cb.recordSuccess('openai') // reset
    cb.recordFailure('openai')
    cb.recordFailure('openai')
    // Only 2 failures since last success
    expect(cb.isAvailable('openai')).toBe(true)
    expect(cb.getStatus().openai.consecutiveFailures).toBe(2)
  })

  test('multiple providers independent tracking', () => {
    const cb = new CircuitBreaker(3, 60_000)
    cb.recordFailure('anthropic')
    cb.recordFailure('anthropic')
    cb.recordFailure('anthropic') // open
    cb.recordFailure('openai')
    cb.recordFailure('openai') // still 2
    cb.recordSuccess('google')

    expect(cb.isAvailable('anthropic')).toBe(false)
    expect(cb.isAvailable('openai')).toBe(true)
    expect(cb.isAvailable('google')).toBe(true)
    expect(cb.getStatus().openai.consecutiveFailures).toBe(2)
    expect(cb.getStatus().google.consecutiveFailures).toBe(0)
  })

  test('custom threshold: 1 failure opens circuit', () => {
    const cb = new CircuitBreaker(1, 60_000)
    cb.recordFailure('anthropic')
    expect(cb.isAvailable('anthropic')).toBe(false)
    expect(cb.getStatus().anthropic.state).toBe('open')
  })

  test('lastFailureAt is set on failure', () => {
    const cb = new CircuitBreaker()
    const before = Date.now()
    cb.recordFailure('anthropic')
    const after = Date.now()
    const status = cb.getStatus()
    expect(status.anthropic.lastFailureAt).toBeGreaterThanOrEqual(before)
    expect(status.anthropic.lastFailureAt).toBeLessThanOrEqual(after)
  })

  test('lastFailureAt is null initially', () => {
    const cb = new CircuitBreaker()
    expect(cb.getStatus().anthropic.lastFailureAt).toBeNull()
  })

  test('default parameters: threshold=3, cooldown=60s', () => {
    const cb = new CircuitBreaker()
    cb.recordFailure('anthropic')
    cb.recordFailure('anthropic')
    expect(cb.isAvailable('anthropic')).toBe(true)
    cb.recordFailure('anthropic')
    expect(cb.isAvailable('anthropic')).toBe(false) // 3 failures = threshold
  })
})

// =====================================================
// TEA: FALLBACK MODEL MAPPING EDGE CASES
// =====================================================

describe('TEA: getFallbackModels edge cases', () => {
  test('all models in catalog have valid provider', () => {
    const models = ['claude-sonnet-4-6', 'claude-haiku-4-5', 'gpt-4.1', 'gpt-4.1-mini', 'gemini-2.5-pro', 'gemini-2.5-flash']
    for (const model of models) {
      const config = getModelConfig(model)
      expect(config).toBeDefined()
      expect(['anthropic', 'openai', 'google']).toContain(config!.provider)
    }
  })

  test('fallback models exclude same provider', () => {
    const fallbacks = getFallbackModels('claude-sonnet-4-6')
    for (const fb of fallbacks) {
      const config = getModelConfig(fb)
      expect(config!.provider).not.toBe('anthropic')
    }
  })

  test('fallback returns exactly 2 models (one per other provider)', () => {
    expect(getFallbackModels('claude-sonnet-4-6').length).toBe(2)
    expect(getFallbackModels('gpt-4.1').length).toBe(2)
    expect(getFallbackModels('gemini-2.5-flash').length).toBe(2)
  })

  test('fallback chain follows fallbackOrder from models.yaml', () => {
    // For anthropic model: next should be openai, then google
    const fb = getFallbackModels('claude-sonnet-4-6')
    expect(getModelConfig(fb[0])!.provider).toBe('openai')
    expect(getModelConfig(fb[1])!.provider).toBe('google')
  })

  test('manager-tier models are higher priced than worker-tier', () => {
    const managerModels = getFallbackModels('claude-sonnet-4-6')
    const workerModels = getFallbackModels('claude-haiku-4-5')

    for (const m of managerModels) {
      expect(getModelConfig(m)!.inputPricePer1M).toBeGreaterThanOrEqual(1)
    }
    for (const m of workerModels) {
      expect(getModelConfig(m)!.inputPricePer1M).toBeLessThan(1)
    }
  })
})

// =====================================================
// TEA: ROUTER FALLBACK RISK SCENARIOS
// =====================================================

describe('TEA: LLMRouter risk scenarios', () => {
  let router: LLMRouter
  let cb: CircuitBreaker

  beforeEach(() => {
    mockGetCredentials.mockReset()
    mockRecordCost.mockReset()
    mockCreateAuditLog.mockReset()
    mockCreateProvider.mockReset()

    mockGetCredentials.mockImplementation(() => Promise.resolve({ api_key: 'key-123' }))
    mockRecordCost.mockImplementation(() => Promise.resolve())
    mockCreateAuditLog.mockImplementation(() => Promise.resolve({ id: 'audit-1' }))

    cb = new CircuitBreaker()
    router = new LLMRouter(cb)
  })

  test('credential failure on fallback provider: tries next', async () => {
    let callCount = 0
    mockGetCredentials.mockImplementation((_cid: string, provider: string) => {
      if (provider === 'openai') return Promise.reject(new Error('No credentials'))
      return Promise.resolve({ api_key: 'key-123' })
    })

    mockCreateProvider.mockImplementation(() => ({
      name: 'anthropic' as LLMProviderName,
      supportsBatch: true,
      call: mock(() => {
        callCount++
        if (callCount === 1) return Promise.reject(makeErr('server_error', 'anthropic'))
        return Promise.resolve(makeResp('gemini-2.5-pro', 'google'))
      }),
      stream: mockAdapterStream,
      estimateCost: () => 0,
    }))

    const result = await router.call(makeRequest('claude-sonnet-4-6'), ctx)
    // Should skip openai (credential failure) and reach google
    expect(result.content).toBe('OK from google')
  })

  test('unknown error code is treated as non-retryable', async () => {
    mockCreateProvider.mockImplementation(() => ({
      name: 'anthropic' as LLMProviderName,
      supportsBatch: true,
      call: mock(() => Promise.reject(makeErr('unknown', 'anthropic'))),
      stream: mockAdapterStream,
      estimateCost: () => 0,
    }))

    // 'unknown' is not in RETRYABLE_CODES, so should not fallback
    try {
      await router.call(makeRequest('claude-sonnet-4-6'), ctx)
      expect(true).toBe(false)
    } catch (err: any) {
      expect(err.code).toBe('unknown')
      // Should only try primary provider
      expect(mockCreateProvider).toHaveBeenCalledTimes(1)
    }
  })

  test('circuit breaker records success on fallback provider', async () => {
    let callCount = 0
    mockCreateProvider.mockImplementation(() => ({
      name: (callCount === 0 ? 'anthropic' : 'openai') as LLMProviderName,
      supportsBatch: true,
      call: mock(() => {
        callCount++
        if (callCount === 1) return Promise.reject(makeErr('server_error', 'anthropic'))
        return Promise.resolve(makeResp('gpt-4.1', 'openai'))
      }),
      stream: mockAdapterStream,
      estimateCost: () => 0,
    }))

    await router.call(makeRequest('claude-sonnet-4-6'), ctx)

    // Anthropic should have 1 failure recorded
    expect(cb.getStatus().anthropic.consecutiveFailures).toBe(1)
    // OpenAI should be healthy (success recorded)
    expect(cb.getStatus().openai.consecutiveFailures).toBe(0)
  })

  test('all circuits open: error mentions circuit breaker', async () => {
    // Open all circuits
    for (const provider of ['anthropic', 'openai', 'google'] as LLMProviderName[]) {
      cb.recordFailure(provider)
      cb.recordFailure(provider)
      cb.recordFailure(provider)
    }

    try {
      await router.call(makeRequest('claude-sonnet-4-6'), ctx)
      expect(true).toBe(false)
    } catch (err: any) {
      expect(err.code).toBe('server_error')
      expect(err.message).toContain('All providers failed')
      expect(err.message).toContain('Circuit breaker open')
    }
  })

  test('cost not recorded when all providers fail', async () => {
    mockCreateProvider.mockImplementation(() => ({
      name: 'anthropic' as LLMProviderName,
      supportsBatch: true,
      call: mock(() => Promise.reject(makeErr('server_error', 'anthropic'))),
      stream: mockAdapterStream,
      estimateCost: () => 0,
    }))

    try {
      await router.call(makeRequest('claude-sonnet-4-6'), ctx)
    } catch { /* expected */ }

    expect(mockRecordCost).not.toHaveBeenCalled()
  })

  test('audit log failure does not break fallback response', async () => {
    let callCount = 0
    mockCreateAuditLog.mockImplementation(() => Promise.reject(new Error('Audit DB down')))

    mockCreateProvider.mockImplementation(() => ({
      name: (callCount === 0 ? 'anthropic' : 'openai') as LLMProviderName,
      supportsBatch: true,
      call: mock(() => {
        callCount++
        if (callCount === 1) return Promise.reject(makeErr('server_error', 'anthropic'))
        return Promise.resolve(makeResp('gpt-4.1', 'openai'))
      }),
      stream: mockAdapterStream,
      estimateCost: () => 0,
    }))

    // Should succeed even though audit log fails
    const result = await router.call(makeRequest('claude-sonnet-4-6'), ctx)
    expect(result.content).toBe('OK from openai')
  })

  test('cost recording failure does not break response', async () => {
    mockRecordCost.mockImplementation(() => Promise.reject(new Error('Cost DB down')))

    mockCreateProvider.mockImplementation(() => ({
      name: 'anthropic' as LLMProviderName,
      supportsBatch: true,
      call: mock(() => Promise.resolve(makeResp('claude-sonnet-4-6', 'anthropic'))),
      stream: mockAdapterStream,
      estimateCost: () => 0,
    }))

    const result = await router.call(makeRequest('claude-sonnet-4-6'), ctx)
    expect(result.content).toBe('OK from anthropic')
  })

  test('getCircuitBreakerStatus reflects real-time state changes', () => {
    expect(router.getCircuitBreakerStatus().anthropic.state).toBe('closed')
    cb.recordFailure('anthropic')
    cb.recordFailure('anthropic')
    cb.recordFailure('anthropic')
    expect(router.getCircuitBreakerStatus().anthropic.state).toBe('open')
    cb.reset()
    expect(router.getCircuitBreakerStatus().anthropic.state).toBe('closed')
  })

  test('worker-tier model uses correct fallback chain', async () => {
    let callCount = 0
    mockCreateProvider.mockImplementation(() => ({
      name: (['anthropic', 'openai'][Math.min(callCount, 1)]) as LLMProviderName,
      supportsBatch: true,
      call: mock(() => {
        callCount++
        if (callCount === 1) return Promise.reject(makeErr('timeout', 'anthropic'))
        return Promise.resolve(makeResp('gpt-4.1-mini', 'openai'))
      }),
      stream: mockAdapterStream,
      estimateCost: () => 0,
    }))

    const result = await router.call(makeRequest('claude-haiku-4-5'), ctx)
    expect(result.model).toBe('gpt-4.1-mini')
  })
})

// =====================================================
// TEA: STREAMING RISK SCENARIOS
// =====================================================

describe('TEA: Streaming fallback risk scenarios', () => {
  let router: LLMRouter
  let cb: CircuitBreaker

  beforeEach(() => {
    mockGetCredentials.mockReset()
    mockRecordCost.mockReset()
    mockCreateAuditLog.mockReset()
    mockCreateProvider.mockReset()

    mockGetCredentials.mockImplementation(() => Promise.resolve({ api_key: 'key' }))
    mockRecordCost.mockImplementation(() => Promise.resolve())
    mockCreateAuditLog.mockImplementation(() => Promise.resolve({ id: 'a1' }))

    cb = new CircuitBreaker()
    router = new LLMRouter(cb)
  })

  test('stream: all providers fail -> aggregated error', async () => {
    mockCreateProvider.mockImplementation(() => ({
      name: 'anthropic' as LLMProviderName,
      supportsBatch: true,
      call: mock(() => Promise.reject(makeErr('server_error'))),
      stream: mock(function* () { throw makeErr('server_error') }),
      estimateCost: () => 0,
    }))

    try {
      const chunks: LLMStreamChunk[] = []
      for await (const chunk of router.stream(makeRequest('claude-sonnet-4-6'), ctx)) {
        chunks.push(chunk)
      }
      expect(true).toBe(false)
    } catch (err: any) {
      expect(err.code).toBe('server_error')
      expect(err.message).toContain('All providers failed')
    }
  })

  test('stream: non-retryable error aborts immediately', async () => {
    mockCreateProvider.mockImplementation(() => ({
      name: 'anthropic' as LLMProviderName,
      supportsBatch: true,
      call: mockAdapterCall,
      stream: mock(function* () { throw makeErr('auth_error') }),
      estimateCost: () => 0,
    }))

    try {
      for await (const _chunk of router.stream(makeRequest('claude-sonnet-4-6'), ctx)) {
        // Should not yield anything
      }
      expect(true).toBe(false)
    } catch (err: any) {
      expect(err.code).toBe('auth_error')
      expect(mockCreateProvider).toHaveBeenCalledTimes(1)
    }
  })

  test('stream: successful primary yields correct usage for cost', async () => {
    mockCreateProvider.mockImplementation(() => ({
      name: 'anthropic' as LLMProviderName,
      supportsBatch: true,
      call: mockAdapterCall,
      stream: mock(function* () {
        yield { type: 'text' as const, content: 'A' }
        yield { type: 'done' as const, usage: { inputTokens: 200, outputTokens: 100 } }
      }),
      estimateCost: () => 0,
    }))

    const chunks: LLMStreamChunk[] = []
    for await (const chunk of router.stream(makeRequest('claude-sonnet-4-6'), ctx)) {
      chunks.push(chunk)
    }
    expect(chunks.length).toBe(2)

    // Verify cost was recorded with correct tokens
    expect(mockRecordCost).toHaveBeenCalledTimes(1)
    const costCall = mockRecordCost.mock.calls[0][0] as any
    expect(costCall.inputTokens).toBe(200)
    expect(costCall.outputTokens).toBe(100)
  })

  test('stream: cost not recorded when no usage reported', async () => {
    mockCreateProvider.mockImplementation(() => ({
      name: 'anthropic' as LLMProviderName,
      supportsBatch: true,
      call: mockAdapterCall,
      stream: mock(function* () {
        yield { type: 'text' as const, content: 'No usage' }
        yield { type: 'done' as const }
      }),
      estimateCost: () => 0,
    }))

    for await (const _chunk of router.stream(makeRequest('claude-sonnet-4-6'), ctx)) {}

    expect(mockRecordCost).not.toHaveBeenCalled()
  })
})
