// Story 1-6: TEA Risk-Based Tests -- Seed Data & Org Templates
// Generated by TEA (Test Architect) automate workflow
import { describe, test, expect } from 'bun:test'
import {
  CHIEF_OF_STAFF_SOUL,
  BUILTIN_TEMPLATES,
  INVESTMENT_TEMPLATE,
  MARKETING_TEMPLATE,
  ALL_IN_ONE_TEMPLATE,
  type TemplateData,
  type TemplateAgent,
  type TemplateDepartment,
} from '../../services/seed.service'

// =============================================
// P0: templateData 스키마 호환성 (DB jsonb 저장 검증)
// =============================================
describe('TEA P0: templateData Schema Compliance', () => {
  const allTemplates = [
    { name: '투자분석', data: INVESTMENT_TEMPLATE },
    { name: '마케팅', data: MARKETING_TEMPLATE },
    { name: '올인원', data: ALL_IN_ONE_TEMPLATE },
  ]

  for (const { name, data } of allTemplates) {
    test(`${name} -- departments는 비어있지 않은 배열이어야 함`, () => {
      expect(Array.isArray(data.departments)).toBe(true)
      expect(data.departments.length).toBeGreaterThan(0)
    })

    test(`${name} -- 모든 부서에 name(string)이 있어야 함`, () => {
      for (const dept of data.departments) {
        expect(typeof dept.name).toBe('string')
        expect(dept.name.length).toBeGreaterThan(0)
      }
    })

    test(`${name} -- 모든 에이전트에 필수 6개 필드가 있어야 함`, () => {
      const requiredFields: (keyof TemplateAgent)[] = ['name', 'role', 'tier', 'modelName', 'soul', 'allowedTools']
      for (const dept of data.departments) {
        for (const agent of dept.agents) {
          for (const field of requiredFields) {
            expect(agent[field]).toBeDefined()
            expect(agent[field]).not.toBeNull()
          }
        }
      }
    })

    test(`${name} -- tier는 정확히 3가지 값 중 하나여야 함`, () => {
      const validTiers = new Set(['manager', 'specialist', 'worker'])
      for (const dept of data.departments) {
        for (const agent of dept.agents) {
          expect(validTiers.has(agent.tier)).toBe(true)
        }
      }
    })

    test(`${name} -- modelName은 claude- 접두사로 시작해야 함`, () => {
      for (const dept of data.departments) {
        for (const agent of dept.agents) {
          expect(agent.modelName).toMatch(/^claude-/)
        }
      }
    })

    test(`${name} -- allowedTools의 모든 항목은 비어있지 않은 string이어야 함`, () => {
      for (const dept of data.departments) {
        for (const agent of dept.agents) {
          for (const tool of agent.allowedTools) {
            expect(typeof tool).toBe('string')
            expect(tool.length).toBeGreaterThan(0)
            expect(tool).not.toContain(' ') // 도구 이름에 공백 없음
          }
        }
      }
    })
  }
})

// =============================================
// P0: 비서실장 Soul 무결성
// =============================================
describe('TEA P0: Chief of Staff Soul Integrity', () => {
  test('Soul이 마크다운 헤딩(#)으로 시작해야 함', () => {
    expect(CHIEF_OF_STAFF_SOUL.trim()).toMatch(/^#/)
  })

  test('Soul에 undefined/null 문자열이 없어야 함', () => {
    expect(CHIEF_OF_STAFF_SOUL).not.toContain('undefined')
    expect(CHIEF_OF_STAFF_SOUL).not.toContain('null')
  })

  test('Soul 길이가 합리적 범위여야 함 (100~5000자)', () => {
    expect(CHIEF_OF_STAFF_SOUL.length).toBeGreaterThan(100)
    expect(CHIEF_OF_STAFF_SOUL.length).toBeLessThan(5000)
  })

  test('재작업 횟수 제한이 명시되어야 함', () => {
    expect(CHIEF_OF_STAFF_SOUL).toContain('최대 2회')
  })
})

// =============================================
// P0: 3계급 모델 배정 정합성
// =============================================
describe('TEA P0: Three-Tier Model Assignment', () => {
  const MANAGER_MODEL = 'claude-sonnet-4-6'
  const NON_MANAGER_MODEL = 'claude-haiku-4-5'

  const allAgents: Array<{ template: string; dept: string; agent: TemplateAgent }> = []
  for (const tmpl of BUILTIN_TEMPLATES) {
    for (const dept of tmpl.templateData.departments) {
      for (const agent of dept.agents) {
        allAgents.push({ template: tmpl.name, dept: dept.name, agent })
      }
    }
  }

  test('Manager 에이전트는 항상 Sonnet 모델이어야 함', () => {
    const managers = allAgents.filter(a => a.agent.tier === 'manager')
    expect(managers.length).toBeGreaterThan(0)
    for (const m of managers) {
      expect(m.agent.modelName).toBe(MANAGER_MODEL)
    }
  })

  test('Specialist 에이전트는 항상 Haiku 모델이어야 함', () => {
    const specialists = allAgents.filter(a => a.agent.tier === 'specialist')
    expect(specialists.length).toBeGreaterThan(0)
    for (const s of specialists) {
      expect(s.agent.modelName).toBe(NON_MANAGER_MODEL)
    }
  })

  test('Worker 에이전트는 항상 Haiku 모델이어야 함', () => {
    const workers = allAgents.filter(a => a.agent.tier === 'worker')
    expect(workers.length).toBeGreaterThan(0)
    for (const w of workers) {
      expect(w.agent.modelName).toBe(NON_MANAGER_MODEL)
    }
  })
})

// =============================================
// P1: allowedTools 유효성 (실제 도구 이름 매칭)
// =============================================
describe('TEA P1: allowedTools Validity', () => {
  // 시드에서 정의된 실제 도구 이름들
  const KNOWN_TOOLS = new Set([
    'get_current_time', 'calculate', 'search_department_knowledge',
    'get_company_info', 'search_web', 'search_news', 'search_images',
    'search_youtube', 'search_places', 'create_report',
    'send_email', 'list_calendar_events', 'create_calendar_event',
    'read_notion_page', 'create_notion_page', 'generate_text_file',
    'get_stock_price', 'get_account_balance', 'place_stock_order',
    'text_to_speech', 'generate_image', 'translate_text',
    'publish_instagram', 'get_instagram_insights',
  ])

  for (const tmpl of BUILTIN_TEMPLATES) {
    for (const dept of tmpl.templateData.departments) {
      for (const agent of dept.agents) {
        test(`${tmpl.name}/${dept.name}/${agent.name} -- 모든 도구가 알려진 도구 목록에 있어야 함`, () => {
          for (const tool of agent.allowedTools) {
            expect(KNOWN_TOOLS.has(tool)).toBe(true)
          }
        })
      }
    }
  }
})

// =============================================
// P1: 부서별 Manager 중복 방지
// =============================================
describe('TEA P1: Department Manager Uniqueness', () => {
  for (const tmpl of BUILTIN_TEMPLATES) {
    for (const dept of tmpl.templateData.departments) {
      test(`${tmpl.name}/${dept.name} -- Manager가 정확히 1명이어야 함 (0명이나 2명 이상 금지)`, () => {
        const managers = dept.agents.filter(a => a.tier === 'manager')
        expect(managers).toHaveLength(1)
      })
    }
  }
})

// =============================================
// P1: 에이전트 이름 고유성 (같은 부서 내)
// =============================================
describe('TEA P1: Agent Name Uniqueness Within Department', () => {
  for (const tmpl of BUILTIN_TEMPLATES) {
    for (const dept of tmpl.templateData.departments) {
      test(`${tmpl.name}/${dept.name} -- 같은 부서 내 에이전트 이름이 고유해야 함`, () => {
        const names = dept.agents.map(a => a.name)
        const uniqueNames = new Set(names)
        expect(uniqueNames.size).toBe(names.length)
      })
    }
  }
})

// =============================================
// P1: 부서 이름 고유성 (같은 템플릿 내)
// =============================================
describe('TEA P1: Department Name Uniqueness Within Template', () => {
  for (const tmpl of BUILTIN_TEMPLATES) {
    test(`${tmpl.name} -- 같은 템플릿 내 부서 이름이 고유해야 함`, () => {
      const names = tmpl.templateData.departments.map(d => d.name)
      const uniqueNames = new Set(names)
      expect(uniqueNames.size).toBe(names.length)
    })
  }
})

// =============================================
// P1: Soul 마크다운에 SQL/코드 인젝션 위험 없음
// =============================================
describe('TEA P1: Soul Content Safety', () => {
  const allSouls: string[] = [CHIEF_OF_STAFF_SOUL]
  for (const tmpl of BUILTIN_TEMPLATES) {
    for (const dept of tmpl.templateData.departments) {
      for (const agent of dept.agents) {
        allSouls.push(agent.soul)
      }
    }
  }

  test('어떤 Soul에도 SQL 키워드가 없어야 함', () => {
    const sqlPatterns = /\b(DROP TABLE|DELETE FROM|INSERT INTO|UPDATE .+ SET|ALTER TABLE)\b/i
    for (const soul of allSouls) {
      expect(sqlPatterns.test(soul)).toBe(false)
    }
  })

  test('어떤 Soul에도 script 태그가 없어야 함', () => {
    for (const soul of allSouls) {
      expect(soul.toLowerCase()).not.toContain('<script')
    }
  })
})

// =============================================
// P2: BUILTIN_TEMPLATES readonly 계약
// =============================================
describe('TEA P2: Template Immutability Contract', () => {
  test('BUILTIN_TEMPLATES 배열 길이가 정확히 3이어야 함', () => {
    expect(BUILTIN_TEMPLATES).toHaveLength(3)
  })

  test('각 템플릿 name이 정확한 한국어여야 함', () => {
    expect(BUILTIN_TEMPLATES[0].name).toBe('투자분석')
    expect(BUILTIN_TEMPLATES[1].name).toBe('마케팅')
    expect(BUILTIN_TEMPLATES[2].name).toBe('올인원')
  })

  test('투자분석 에이전트 수가 정확히 5명이어야 함', () => {
    const count = INVESTMENT_TEMPLATE.departments.reduce((s, d) => s + d.agents.length, 0)
    expect(count).toBe(5)
  })

  test('마케팅 에이전트 수가 정확히 4명이어야 함', () => {
    const count = MARKETING_TEMPLATE.departments.reduce((s, d) => s + d.agents.length, 0)
    expect(count).toBe(4)
  })

  test('올인원 에이전트 수가 정확히 12명이어야 함', () => {
    const count = ALL_IN_ONE_TEMPLATE.departments.reduce((s, d) => s + d.agents.length, 0)
    expect(count).toBe(12)
  })
})

// =============================================
// P2: Manager 에이전트에 create_report 도구 포함 확인
// =============================================
describe('TEA P2: Manager Report Capability', () => {
  for (const tmpl of BUILTIN_TEMPLATES) {
    for (const dept of tmpl.templateData.departments) {
      const manager = dept.agents.find(a => a.tier === 'manager')
      if (manager) {
        test(`${tmpl.name}/${dept.name}/${manager.name} -- Manager에 create_report 도구가 있어야 함`, () => {
          expect(manager.allowedTools).toContain('create_report')
        })
      }
    }
  }
})
