/**
 * Story 12.4: A/B 품질 테스트 프레임워크 — TEA Risk-Based Tests
 *
 * Generated by TEA (Test Architect) — risk-based coverage expansion.
 * Covers: error handling, boundary conditions, data integrity, negative paths.
 */

import { describe, test, expect } from 'bun:test'
import { AB_PROMPTS, AB_CATEGORIES } from '../fixtures/ab-prompts'
import {
  loadV1Snapshots,
  calculateDelta,
  compareResults,
  generateSummary,
  generateDryRunV2Snapshots,
  saveReport,
  type ABSnapshot,
  type ABComparisonResult,
  type ABTestReport,
} from '../../../scripts/ab-quality-test'
import { join } from 'path'
import { mkdirSync, rmSync, existsSync } from 'fs'

// ─── Risk: Malformed/Corrupted Snapshot Data (P0) ───────────

describe('TEA Risk: Malformed Snapshot Handling', () => {
  test('loadV1Snapshots throws on invalid JSON path', () => {
    expect(() => loadV1Snapshots('/nonexistent/path.json')).toThrow()
  })

  test('calculateDelta handles negative tool call counts gracefully', () => {
    const v1: ABSnapshot = {
      promptId: 'test', model: 'm', response: 'abc',
      tokenCount: 100, durationMs: 1000, toolCallCount: 5, handoffDepth: 3,
    }
    const v2: ABSnapshot = {
      promptId: 'test', model: 'm', response: 'ab',
      tokenCount: 50, durationMs: 500, toolCallCount: 0, handoffDepth: 0,
    }
    const delta = calculateDelta(v1, v2)
    expect(delta.toolCallDiff).toBe(-5)
    expect(delta.handoffDepthDiff).toBe(-3)
    expect(delta.responseLengthRatio).toBeLessThan(1)
  })

  test('calculateDelta handles very large response strings', () => {
    const largeStr = 'x'.repeat(1_000_000)
    const v1: ABSnapshot = {
      promptId: 'test', model: 'm', response: 'small',
      tokenCount: 10, durationMs: 100, toolCallCount: 0, handoffDepth: 0,
    }
    const v2: ABSnapshot = {
      promptId: 'test', model: 'm', response: largeStr,
      tokenCount: 999999, durationMs: 60000, toolCallCount: 0, handoffDepth: 0,
    }
    const delta = calculateDelta(v1, v2)
    expect(delta.responseLengthRatio).toBe(200000) // 1M / 5
    expect(Number.isFinite(delta.responseLengthRatio)).toBe(true)
  })
})

// ─── Risk: Prompt-Snapshot ID Mismatch (P1) ─────────────────

describe('TEA Risk: Prompt-Snapshot Alignment', () => {
  test('compareResults returns empty when no v1 snapshots match', () => {
    const v1: ABSnapshot[] = [
      { promptId: 'unknown-01', model: 'm', response: 'x', tokenCount: 0, durationMs: 0, toolCallCount: 0, handoffDepth: 0 },
    ]
    const v2: ABSnapshot[] = AB_PROMPTS.map(p => ({
      promptId: p.id, model: 'm', response: 'x', tokenCount: 0, durationMs: 0, toolCallCount: 0, handoffDepth: 0,
    }))
    const results = compareResults(v1, v2, AB_PROMPTS)
    expect(results).toHaveLength(0)
  })

  test('compareResults returns empty when no v2 snapshots match', () => {
    const snapshotPath = join(__dirname, '../fixtures/ab-snapshots/v1-baseline.json')
    const v1 = loadV1Snapshots(snapshotPath)
    const v2: ABSnapshot[] = [] // no v2 results
    const results = compareResults(v1, v2, AB_PROMPTS)
    expect(results).toHaveLength(0)
  })

  test('compareResults handles partial overlap correctly', () => {
    const v1: ABSnapshot[] = [
      { promptId: 'translate-01', model: 'm', response: 'x', tokenCount: 0, durationMs: 0, toolCallCount: 0, handoffDepth: 0 },
      { promptId: 'coding-01', model: 'm', response: 'y', tokenCount: 0, durationMs: 0, toolCallCount: 0, handoffDepth: 0 },
    ]
    const v2: ABSnapshot[] = [
      { promptId: 'translate-01', model: 'm', response: 'xx', tokenCount: 0, durationMs: 0, toolCallCount: 0, handoffDepth: 0 },
      // coding-01 missing in v2
    ]
    const results = compareResults(v1, v2, AB_PROMPTS)
    expect(results).toHaveLength(1)
    expect(results[0].promptId).toBe('translate-01')
  })
})

// ─── Risk: Summary Calculation Edge Cases (P0) ──────────────

describe('TEA Risk: Summary Edge Cases', () => {
  test('generateSummary handles single result', () => {
    const results: ABComparisonResult[] = [{
      promptId: 'a', category: 'coding',
      v1: { promptId: 'a', model: 'm', response: 'x', tokenCount: 0, durationMs: 0, toolCallCount: 0, handoffDepth: 0 },
      v2: { promptId: 'a', model: 'm', response: 'x', tokenCount: 0, durationMs: 0, toolCallCount: 0, handoffDepth: 0 },
      delta: { responseLengthRatio: 2.5, toolCallDiff: 3, handoffDepthDiff: -1, completenessScore: 9 },
    }]
    const summary = generateSummary(results)
    expect(summary.avgResponseLengthRatio).toBe(2.5)
    expect(summary.avgToolCallDiff).toBe(3)
    expect(summary.avgHandoffDepthDiff).toBe(-1)
    expect(summary.avgCompletenessScore).toBe(9)
  })

  test('generateSummary rounds to 2 decimal places', () => {
    const results: ABComparisonResult[] = [
      {
        promptId: 'a', category: 'coding',
        v1: { promptId: 'a', model: 'm', response: 'x', tokenCount: 0, durationMs: 0, toolCallCount: 0, handoffDepth: 0 },
        v2: { promptId: 'a', model: 'm', response: 'x', tokenCount: 0, durationMs: 0, toolCallCount: 0, handoffDepth: 0 },
        delta: { responseLengthRatio: 1.333, toolCallDiff: 1, handoffDepthDiff: 0, completenessScore: 7 },
      },
      {
        promptId: 'b', category: 'coding',
        v1: { promptId: 'b', model: 'm', response: 'x', tokenCount: 0, durationMs: 0, toolCallCount: 0, handoffDepth: 0 },
        v2: { promptId: 'b', model: 'm', response: 'x', tokenCount: 0, durationMs: 0, toolCallCount: 0, handoffDepth: 0 },
        delta: { responseLengthRatio: 1.666, toolCallDiff: 2, handoffDepthDiff: 1, completenessScore: 8 },
      },
    ]
    const summary = generateSummary(results)
    // (1.333 + 1.666) / 2 = 1.4995 → rounds to 1.5
    expect(summary.avgResponseLengthRatio).toBe(1.5)
    expect(summary.avgToolCallDiff).toBe(1.5)
    expect(summary.avgHandoffDepthDiff).toBe(0.5)
    expect(summary.avgCompletenessScore).toBe(7.5)
  })
})

// ─── Risk: Report File I/O (P2) ─────────────────────────────

describe('TEA Risk: Report Save/Load', () => {
  const tmpDir = join(__dirname, '../../../__tmp_tea_test__')

  test('saveReport creates output directory and file', () => {
    // Clean up first
    if (existsSync(tmpDir)) rmSync(tmpDir, { recursive: true })

    const report: ABTestReport = {
      generatedAt: '2026-03-11T00:00:00Z',
      mode: 'dry-run',
      totalPrompts: 2,
      results: [],
      summary: { avgResponseLengthRatio: 0, avgToolCallDiff: 0, avgHandoffDepthDiff: 0, avgCompletenessScore: 0 },
    }
    const path = saveReport(report, tmpDir)
    expect(existsSync(path)).toBe(true)
    expect(path).toContain('ab-results-')
    expect(path).toEndWith('.json')
    // Timestamp format: ab-results-YYYY-MM-DDTHH-MM-SS-MMMZ.json
    expect(path).toMatch(/ab-results-\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}/)

    // Cleanup
    rmSync(tmpDir, { recursive: true })
  })
})

// ─── Risk: Dry Run Mock Data Integrity (P1) ─────────────────

describe('TEA Risk: Dry Run Data Integrity', () => {
  test('dry run snapshots have unique prompt IDs matching input', () => {
    const v2 = generateDryRunV2Snapshots(AB_PROMPTS)
    const ids = v2.map(s => s.promptId)
    const inputIds = AB_PROMPTS.map(p => p.id)
    expect(ids).toEqual(inputIds)
  })

  test('dry run with empty prompt list returns empty', () => {
    const v2 = generateDryRunV2Snapshots([])
    expect(v2).toHaveLength(0)
  })

  test('dry run with single prompt returns single snapshot', () => {
    const v2 = generateDryRunV2Snapshots([AB_PROMPTS[0]])
    expect(v2).toHaveLength(1)
    expect(v2[0].promptId).toBe(AB_PROMPTS[0].id)
  })
})

// ─── Risk: AB_CATEGORIES Const Correctness (P2) ─────────────

describe('TEA Risk: Category Constants', () => {
  test('AB_CATEGORIES matches actual prompt categories', () => {
    const actualCategories = [...new Set(AB_PROMPTS.map(p => p.category))].sort()
    const definedCategories = [...AB_CATEGORIES].sort()
    expect(actualCategories).toEqual(definedCategories)
  })

  test('AB_CATEGORIES is readonly tuple', () => {
    // TypeScript enforces this, but verify length
    expect(AB_CATEGORIES).toHaveLength(5)
  })
})
