/**
 * Go/No-Go #4 — Zero Regression: Agent Memories Extension (Story 28.5)
 *
 * Verify existing agent_memories queries still work after schema extension.
 * Tests source file structure — no real DB connection needed.
 */
import { describe, test, expect } from 'bun:test'

const schemaPath = 'packages/server/src/db/schema.ts'
const queryPath = 'packages/server/src/db/scoped-query.ts'
const migrationPath = 'packages/server/src/db/migrations/0064_agent_memories_extension.sql'

describe('Go/No-Go #4 — Agent Memories Extension Zero Regression', () => {
  // ── Item 1: Schema backward compatibility ──────────────────

  test('schema: agent_memories retains all original columns', async () => {
    const schema = await Bun.file(schemaPath).text()
    // Original columns must still exist
    const requiredColumns = [
      "id: uuid('id')",
      "companyId: uuid('company_id')",
      "agentId: uuid('agent_id')",
      "memoryType: memoryTypeEnum('memory_type')",
      "key: varchar('key'",
      "content: text('content')",
      "context: text('context')",
      "source: varchar('source'",
      "confidence: integer('confidence')",
      "usageCount: integer('usage_count')",
      "lastUsedAt: timestamp('last_used_at')",
      "isActive: boolean('is_active')",
      "createdAt: timestamp('created_at')",
      "updatedAt: timestamp('updated_at')",
    ]
    for (const col of requiredColumns) {
      expect(schema).toContain(col)
    }
  })

  test('schema: new columns added (embedding, category, observationIds)', async () => {
    const schema = await Bun.file(schemaPath).text()
    expect(schema).toContain("embedding: vector('embedding', { dimensions: 1024 })")
    expect(schema).toContain("category: varchar('category'")
    expect(schema).toContain("observationIds: text('observation_ids')")
  })

  test('schema: original indexes preserved', async () => {
    const schema = await Bun.file(schemaPath).text()
    expect(schema).toContain("agent_memories_company_idx")
    expect(schema).toContain("agent_memories_agent_idx")
    expect(schema).toContain("agent_memories_type_idx")
  })

  test('schema: source default is still "manual"', async () => {
    const schema = await Bun.file(schemaPath).text()
    expect(schema).toContain(".default('manual')")
  })

  test('schema: confidence default is still 50', async () => {
    const schema = await Bun.file(schemaPath).text()
    expect(schema).toContain(".default(50)")
  })

  // ── Item 2: Migration safety ───────────────────────────────

  test('migration: uses IF NOT EXISTS for all ALTERs', async () => {
    const migration = await Bun.file(migrationPath).text()
    expect(migration).toContain('ADD COLUMN IF NOT EXISTS embedding VECTOR(1024)')
    expect(migration).toContain('ADD COLUMN IF NOT EXISTS category VARCHAR(50)')
    expect(migration).toContain('ADD COLUMN IF NOT EXISTS observation_ids')
  })

  test('migration: HNSW index uses vector_cosine_ops', async () => {
    const migration = await Bun.file(migrationPath).text()
    expect(migration).toContain('USING hnsw (embedding vector_cosine_ops)')
    expect(migration).toContain('CREATE INDEX IF NOT EXISTS idx_agent_memories_embedding')
  })

  test('migration: partial index for reflection memories', async () => {
    const migration = await Bun.file(migrationPath).text()
    expect(migration).toContain('idx_agent_memories_reflection')
    expect(migration).toContain("WHERE source = 'reflection'")
  })

  // ── Item 3: Existing scoped-query methods unchanged ────────

  test('scoped-query: insertReflectionMemory still works with old signature', async () => {
    const query = await Bun.file(queryPath).text()
    expect(query).toContain('insertReflectionMemory')
    expect(query).toContain("source: 'reflection'")
    expect(query).toContain("context: 'auto-generated by reflection cron'")
  })

  test('scoped-query: existing observation methods intact', async () => {
    const query = await Bun.file(queryPath).text()
    expect(query).toContain('countUnreflectedObservations')
    expect(query).toContain('getUnreflectedObservations')
    expect(query).toContain('markObservationsReflected')
    expect(query).toContain('listObservations')
    expect(query).toContain('updateObservationEmbedding')
  })

  // ── Item 4: New methods exist ──────────────────────────────

  test('scoped-query: new Story 28.5 methods exist', async () => {
    const query = await Bun.file(queryPath).text()
    expect(query).toContain('searchMemoriesBySimilarity')
    expect(query).toContain('listAgentMemories')
    expect(query).toContain('deleteAgentMemory')
    expect(query).toContain('updateMemoryConfidence')
    expect(query).toContain('updateAgentMemoryEmbedding')
  })

  // ── Item 5: Reflection worker vectorization ────────────────

  test('reflection-worker: imports getEmbedding for vectorization', async () => {
    const worker = await Bun.file('packages/server/src/services/reflection-worker.ts').text()
    expect(worker).toContain("import { getEmbedding } from './voyage-embedding'")
  })

  test('reflection-worker: fire-and-forget vectorize after memory insert', async () => {
    const worker = await Bun.file('packages/server/src/services/reflection-worker.ts').text()
    expect(worker).toContain('updateAgentMemoryEmbedding')
    expect(worker).toContain('getEmbedding(companyId')
  })
})
