"use client";
import React from "react";

const styles = `
body {
            background-color: #F4F4F0;
            color: #1E1E1E;
        }

        .neo-border {
            border: 3px solid #1E1E1E;
        }

        .neo-shadow {
            box-shadow: 4px 4px 0px 0px rgba(30, 30, 30, 1);
        }

        .neo-shadow-sm {
            box-shadow: 2px 2px 0px 0px rgba(30, 30, 30, 1);
        }

        .neo-card {
            border: 3px solid #1E1E1E;
            box-shadow: 8px 8px 0px 0px rgba(30, 30, 30, 1);
            background-color: white;
        }

        .neo-btn {
            border: 3px solid #1E1E1E;
            box-shadow: 4px 4px 0px 0px rgba(30, 30, 30, 1);
            transition: all 0.1s ease-in-out;
            font-weight: 700;
            cursor: pointer;
        }

        .neo-btn:hover {
            transform: translate(-2px, -2px);
            box-shadow: 6px 6px 0px 0px rgba(30, 30, 30, 1);
        }

        .neo-btn:active {
            transform: translate(4px, 4px);
            box-shadow: 0px 0px 0px 0px rgba(30, 30, 30, 1);
        }

        .nav-item.active {
            background-color: #00E5FF;
            border: 3px solid #1E1E1E;
            box-shadow: 2px 2px 0px 0px rgba(30, 30, 30, 1);
        }

        .nav-item:hover:not(.active) {
            background-color: #E5E5E5;
        }

        ::-webkit-scrollbar {
            width: 10px;
            height: 10px;
            border-left: 3px solid #1E1E1E;
            border-top: 3px solid #1E1E1E;
        }

        ::-webkit-scrollbar-track {
            background: #F4F4F0;
        }

        ::-webkit-scrollbar-thumb {
            background: #1E1E1E;
            border: 2px solid #F4F4F0;
        }

        .admin-bg {
            background-image:
                linear-gradient(45deg, #00E5FF 25%, transparent 25%, transparent 75%, #00E5FF 75%, #00E5FF),
                linear-gradient(45deg, #00E5FF 25%, transparent 25%, transparent 75%, #00E5FF 75%, #00E5FF);
            background-size: 10px 10px;
            background-position: 0 0, 5px 5px;
            opacity: 0.1;
        }
`;

function AdminApiKeys() {
  return (
    <>{"
"}
      <style dangerouslySetInnerHTML={{__html: styles}} />
<div className="absolute inset-0 admin-bg z-[-1] pointer-events-none"></div>

    <header
        className="h-16 border-b-3 border-neo-black bg-white flex items-center justify-between px-6 z-30 shrink-0 sticky top-0 shadow-[0px_4px_0px_#1E1E1E]">
        <div className="flex items-center gap-4">
            <h1 className="text-2xl font-black tracking-tight uppercase flex items-center gap-2">
                <span className="bg-neo-pink text-white px-2 border-2 border-black rotate-[-2deg] shadow-sm">CORTHEX</span>
                ADMIN
            </h1>
        </div>
        <div className="flex items-center gap-4">
            <div
                className="w-10 h-10 bg-neo-lime rounded-full border-3 border-neo-black shadow-sm flex items-center justify-center font-black">
                SW</div>
        </div>
    </header>

    <div className="flex h-[calc(100vh-4rem)]">

        <nav className="w-64 border-r-3 border-neo-black bg-white flex flex-col h-full z-10 shrink-0 overflow-y-auto">
            <div className="p-4 space-y-1">
                <p className="text-[10px] uppercase font-black tracking-widest text-gray-400 mt-2 mb-1 pl-2">Platform
                    Overview</p>
                <a href="/admin/dashboard"
                    className="nav-item flex items-center gap-3 p-2 font-bold transition-colors text-sm">🏢 Dashboard</a>
                <a href="/admin/companies"
                    className="nav-item flex items-center gap-3 p-2 font-bold transition-colors text-sm">🌐 Companies
                    (Tenants)</a>
                <a href="/admin/api-keys"
                    className="nav-item active flex items-center gap-3 p-2 font-bold transition-colors text-sm">🔑 Tenant
                    API Keys</a>
                <a href="/admin/costs"
                    className="nav-item flex items-center gap-3 p-2 font-bold transition-colors text-sm">💸 Billing &
                    Tokens</a>
            </div>
        </nav>

        <main className="flex-grow flex flex-col h-full bg-transparent overflow-y-auto w-full p-8 relative z-0">
            <div className="max-w-6xl mx-auto w-full space-y-8">

                <div
                    className="flex justify-between items-center bg-white p-6 border-3 border-neo-black shadow-[8px_8px_0px_#1E1E1E]">
                    <div>
                        <h2 className="text-3xl font-black uppercase text-neo-blue tracking-tight">Tenant API Key Management
                        </h2>
                        <p className="font-bold text-gray-600 mt-1 text-sm">Monitor and manage the API keys generated by
                            tenants for external system integrations.</p>
                    </div>
                </div>

                <div className="neo-card bg-white p-6">

                    <div className="flex flex-wrap gap-4 items-center mb-6">
                        <input type="text" placeholder="Search keys or tenants..."
                            className="p-2 border-3 border-neo-black bg-neo-bg font-bold w-72 focus:outline-none focus:bg-white focus:ring-2 focus:ring-neo-blue shadow-[2px_2px_0px_#000]" />
                        <select
                            className="p-2 border-3 border-neo-black bg-white font-bold cursor-pointer outline-none shadow-[2px_2px_0px_#000]">
                            <option>All Statuses</option>
                            <option>Active</option>
                            <option>Revoked</option>
                            <option>Expired</option>
                        </select>
                    </div>

                    {/* API: GET /api/admin/api-keys */}
                    <table className="w-full text-left font-medium border-collapse">
                        <thead
                            className="bg-neo-black text-white text-xs uppercase font-black tracking-widest border-b-3 border-neo-black">
                            <tr>
                                <th className="p-4 border-r-2 border-gray-700">Key Name / Tenant</th>
                                <th className="p-4 border-r-2 border-gray-700">Prefix</th>
                                <th className="p-4 border-r-2 border-gray-700 text-center">Created</th>
                                <th className="p-4 border-r-2 border-gray-700 text-center">Status</th>
                                <th className="p-4 text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y-3 divide-gray-200 border-x-3 border-b-3 border-neo-black">

                            {/* Key 1 */}
                            <tr className="hover:bg-neo-blue/10 transition-colors">
                                <td className="p-4 border-r-3 border-black">
                                    <div className="font-black text-sm">Zendesk Integration</div>
                                    <div className="text-xs font-bold text-gray-500 mt-1">Tenant: <span
                                            className="text-black bg-gray-200 px-1 border border-black">Acme Corp</span>
                                    </div>
                                </td>
                                <td className="p-4 border-r-3 border-black">
                                    <span className="font-mono text-sm bg-gray-100 p-1 neo-border">ctx_live_aBcDeF...</span>
                                </td>
                                <td className="p-4 border-r-3 border-black text-center text-sm font-bold">2024-03-15</td>
                                <td className="p-4 border-r-3 border-black text-center">
                                    <span
                                        className="bg-neo-lime text-black px-2 py-0.5 border-2 border-black text-[10px] font-black uppercase shadow-sm">Active</span>
                                </td>
                                <td className="p-4 text-center">
                                    {/* API: POST /api/admin/api-keys/:id/revoke */}
                                    <button
                                        className="bg-white text-neo-pink border-2 border-neo-pink px-3 py-1 text-[10px] font-black uppercase shadow-[2px_2px_0px_#FF3366] hover:bg-neo-pink hover:text-white transition-colors">Revoke</button>
                                </td>
                            </tr>

                            {/* Key 2 */}
                            <tr className="hover:bg-neo-blue/10 transition-colors">
                                <td className="p-4 border-r-3 border-black">
                                    <div className="font-black text-sm">Zapier Auth</div>
                                    <div className="text-xs font-bold text-gray-500 mt-1">Tenant: <span
                                            className="text-black bg-gray-200 px-1 border border-black">Global Tech</span>
                                    </div>
                                </td>
                                <td className="p-4 border-r-3 border-black">
                                    <span className="font-mono text-sm bg-gray-100 p-1 neo-border">ctx_live_XyZ123...</span>
                                </td>
                                <td className="p-4 border-r-3 border-black text-center text-sm font-bold">2024-02-10</td>
                                <td className="p-4 border-r-3 border-black text-center">
                                    <span
                                        className="bg-neo-pink text-white px-2 py-0.5 border-2 border-black text-[10px] font-black uppercase shadow-sm">Revoked</span>
                                </td>
                                <td className="p-4 text-center">
                                    <button
                                        className="bg-gray-200 text-gray-400 border-2 border-gray-300 px-3 py-1 text-[10px] font-black uppercase cursor-not-allowed"
                                        disabled>Revoked</button>
                                </td>
                            </tr>

                            {/* Key 3 */}
                            <tr className="hover:bg-neo-blue/10 transition-colors">
                                <td className="p-4 border-r-3 border-black">
                                    <div className="font-black text-sm">Custom Dashboard Webhook</div>
                                    <div className="text-xs font-bold text-gray-500 mt-1">Tenant: <span
                                            className="text-black bg-gray-200 px-1 border border-black">Beta Startup</span>
                                    </div>
                                </td>
                                <td className="p-4 border-r-3 border-black">
                                    <span className="font-mono text-sm bg-gray-100 p-1 neo-border">ctx_test_987qWe...</span>
                                </td>
                                <td className="p-4 border-r-3 border-black text-center text-sm font-bold">2024-04-01</td>
                                <td className="p-4 border-r-3 border-black text-center">
                                    <span
                                        className="bg-neo-yellow text-black px-2 py-0.5 border-2 border-black text-[10px] font-black uppercase shadow-sm">Test
                                        Mode</span>
                                </td>
                                <td className="p-4 text-center">
                                    <button
                                        className="bg-white text-neo-pink border-2 border-neo-pink px-3 py-1 text-[10px] font-black uppercase shadow-[2px_2px_0px_#FF3366] hover:bg-neo-pink hover:text-white transition-colors">Revoke</button>
                                </td>
                            </tr>

                        </tbody>
                    </table>
                </div>

            </div>
        </main>
    </div>
    </>
  );
}

export default AdminApiKeys;
