export const ERROR_CODES = {
  // Legacy numeric → descriptive (D3)
  AUTH_001: 'AUTH_INVALID_CREDENTIALS',
  AUTH_002: 'AUTH_TOKEN_EXPIRED',
  AUTH_003: 'AUTH_FORBIDDEN',
  AGENT_001: 'AGENT_NOT_FOUND',
  RATE_001: 'RATE_LIMIT_EXCEEDED',

  // Engine-specific codes
  AGENT_SPAWN_FAILED: 'AGENT_SPAWN_FAILED',
  AGENT_TIMEOUT: 'AGENT_TIMEOUT',
  SESSION_LIMIT_EXCEEDED: 'SESSION_LIMIT_EXCEEDED',
  HANDOFF_DEPTH_EXCEEDED: 'HANDOFF_DEPTH_EXCEEDED',
  HANDOFF_CIRCULAR: 'HANDOFF_CIRCULAR',
  HANDOFF_TARGET_NOT_FOUND: 'HANDOFF_TARGET_NOT_FOUND',
  TOOL_PERMISSION_DENIED: 'TOOL_PERMISSION_DENIED',
  HOOK_PIPELINE_ERROR: 'HOOK_PIPELINE_ERROR',
  SERVER_SHUTTING_DOWN: 'SERVER_SHUTTING_DOWN',
  ORG_SECRETARY_DELETE_DENIED: 'ORG_SECRETARY_DELETE_DENIED',

  // Credential errors (E11, D3 extension — Story 16.3)
  CREDENTIAL_TEMPLATE_UNRESOLVED: 'CREDENTIAL_TEMPLATE_UNRESOLVED',
} as const

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES]
